### ISSUE TITLE
F# port

### ISSUE THREAD

**Issue by markvincze** [benjamin-hodgson/Pidgin#1]
Hey Benjamin,

I couldn't find any other way to contact you, that's why I created an issue.

Just wanted to mention that after your NDC talk I got curious what the syntax of Pidgin would look like in F#, so I started to work on a port, which now has enough functionality to implement a simple Json parser. The implementation closely follows the primitive and complex parsers of Pidgin, although a couple of them had to be renamed due to reserved F# keywords (for example I used `after` instead of `then`).

Many things are still missing, mainly some of the more finicky parsers (`SeparatedAndOptionallyTerminated`, etc.), error messages, backtracking, and any other parser state than strings. Also, I started working on it mainly to learn more about F#, so it's not really intended for production use (for which there is already FParsec anyway).

So far what I really liked about doing it in F#:
 - Pattern matching (with warnings if it's not exhaustive)
 - The partial application and function composition leads to some really terse syntax
 - Type inference, mainly not having to specify the argument types and the generic type arguments
 - Defining mutually recursive parsers is really easy with the `and` syntax

What I didn't like:
 - No function overloading, so there is no way to have `map` with different number of arguments
 - The current syntax of advancing the parser state (`let newState = advance state`) suggests that the state is immutable, which is true for a string state but wouldn't be true in the case of a stream (not implemented yet). I'm not sure yet what the nicest way to express this would be.

If you're interested, you can take a look [here](https://github.com/markvincze/PidginFsharp).

Cheers,
Mark

**Comment by benjamin-hodgson** [comment]
Cool! Glad you enjoyed the talk and that it inspired you to write some code 😄

Regarding your questions:
* In F#, which has infix operators, I'd probably go with an [`Applicative`](https://hackage.haskell.org/package/base-4.9.1.0/docs/Control-Applicative.html)-style API for what I called `Map` in C#. `Map(f, x, y, z)` becomes `f <$> x <*> y <*> z`.
* FParsec stores its input stream imperatively, in a [mutable shared object](https://github.com/stephan-tolksdorf/fparsec/blob/master/FParsecCS/CharStreamLT.cs). [I made a similar decision for Pidgin](https://github.com/benjamin-hodgson/Pidgin/tree/master/Pidgin/ParseStates). You wanna avoid creating and discarding lots of immutable objects on the heap in high throughput code, so I think the risks of using a shared mutable object are worth it in this instance. I decided to keep `IParseState` internal, and I make sure that each `IParseState` object doesn't live longer than a single invocation of the parser, to keep the imperative parts of the library hidden from clients. 
  * There are other options here though. Looking at two Haskell libraries I was influenced by: [`attoparsec`](https://hackage.haskell.org/package/attoparsec) incrementally reads its input into an array (which is mutable under the hood but has an immutable interface). [`megaparsec`](https://hackage.haskell.org/package/megaparsec) works over immutable streams with a cheap `uncons`, so the input stream becomes garbage one token at a time (except for backtracking). All the Haskell parsing libs I know of represent a parser as a higher-order function and work in continuation passing style, relying on compile time inlining to generate fast code. (Clearly this would not work in C#.)

I'd definitely recommend FParsec for production use in F#. It's mature, stable and fast. But writing a library for yourself is still a good idea, it's the best way to get to grips with how it works and to get a sense of the design space. (Pidgin is probably the 4th or 5th parser combinator library I've written, in a variety of languages, it's just the first one I've published 😉).

Hopefully I wasn't too rambly and there was some interesting stuff in there :)

**Comment by markvincze** [comment]
Hi @benjamin-hodgson,

Thanks for the response 😃
Yeah, halfway through I realized that a naive immutable model probably won't cut it, already because it doesn't model how a stream works, so probably I'll switch to a mutable model.

Thanks for the suggestions about the Applicative-style API, and the references to the Haskell libraries, I'll check them out!

>But writing a library for yourself is still a good idea, it's the best way to get to grips with how it works and to get a sense of the design space.
And the parser domain was really fun to work with to learn some more F#, and also the codebase of Pidgin is super clean and easy to follow 😉.

Cheers,
Mark
