### ISSUE TITLE
[Question] Is Map the best way to build an object from multiple parsers?

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [benjamin-hodgson/Pidgin#10]
First thank you for this library, I have some monster regexs that i can make more maintainable with this =D

But, I have some difficulty composing a parser that emits a complex type.

I have a string like this
```
Bob Saget : (1234) 'Actor' 
```

And an object like this 

```c#
class Person
{
    public string Name { get; set; }
    public int Id { get; set; }
    public string Title { get; set; }
}
```

And a few parsers defined like this 

```c#
var Colon = Char(':');
var SingleQuote = Char('\'');
var Name = OneOf(Letter, Whitespace).ManyString();
var IdNumber = Num.Between(Char('('), Char(')'));
var Title = OneOf(Letter, Whitespace).Many().Between(SingleQuote).Select(chars => string.Concat(chars));
```
But I am having a hard time chaining my primitive parsers into a single complex parser without losing the data from early stages in the pipeline. 

Ideally i would like a `Result<char, Person>`. To accomplish this I have awkwardly 'mapped' them together like this.

```c#
Person MakePerson(string name, char _, char _, int id, char _, string title)
{ 
    return new Person {
      Name = name, 
      Id = id,
      Title = title
    };
}

var personParser = Map(MakePerson, Name, Colon, Whitespace, IdNumber, Whitespace, Title);
```
It works, but if i had 10 properties or more discards I would be out of luck for using map. 

The given sequencing primitives (Then and Before) assume one of the two captures are not useful so if i don't have throwaway characters to burn i am not sure how to use them.  I might just be bad at parser combinators but this has me kinda stumped.

I have fought this making by a fluent builder that flows state, very similar to a F# computation expression like this.

```C#
public static class Builder
{
    public static Builder<TToken, TComplex, TToken> Create<TToken, TComplex>(IEnumerable<TToken> tokenStream, TComplex item) => new Builder<TToken, TComplex, TToken>(tokenStream, item);
}

public struct Builder<TToken, TComplex, TLast>
{
    public IEnumerator<TToken> Enumerator { get; }
    public TComplex Item { get; }

    public Result<TToken, TLast>? LastResult { get; }
    public Builder(IEnumerable<TToken> tokenStream, TComplex item)
    {
        Enumerator = tokenStream.GetEnumerator();
        Item = item;
        LastResult = null;
    }

    private Builder(IEnumerator<TToken> enumerator, TComplex item, Result<TToken, TLast> lastResult)
    {
        Enumerator = enumerator;
        Item = item;
        LastResult = lastResult;
    }

    private bool ResultOk => LastResult == null || LastResult.Value.Success;

    public Builder<TToken, TComplex, T2> Capture<T2>(Parser<TToken, T2> parser, Action<TComplex, T2> assignment)
    {
        if (!ResultOk)
            return new Builder<TToken, TComplex, T2>(Enumerator, Item, new Result<TToken, T2>());

        var newResult = parser.Parse(Enumerator);

        if (newResult.Success)
            assignment(Item, newResult.Value);

        return new Builder<TToken, TComplex, T2>(Enumerator, Item, newResult);
    }

    public Builder<TToken, TComplex, T2> Skip<T2>(Parser<TToken, T2> parser)
    {
        if (!ResultOk)
            return new Builder<TToken, TComplex, T2>(Enumerator, Item, new Result<TToken, T2>());

        return new Builder<TToken, TComplex, T2>(Enumerator, Item, parser.Parse(Enumerator));
    }


    public Result<TToken, TComplex> Done
    {
        get
        {
            Parser<TToken, TComplex> ret;
            if (ResultOk)
                ret = Parser<TToken>.Return(Item);
            else
                ret = Parser<TToken>.Fail<TComplex>();

            return ret.Parse(Enumerable.Empty<TToken>());
        }
    }
}
```

Which i then use like this

```c#
var result =
    Builder
    .Create(testSubject, new Employ())
    .Capture(Name, (e, name) => e.Name = name)
    .Skip(Colon)
    .Skip(Whitespace)
    .Capture(IdNumber, (e, id) => e.Id = id)
    .Skip(Whitespace)
    .Capture(Title, (e, title) => e.Title = title)
    .Done;
```

My questions are 
1. Is there a more idiomatic way to chain simple parsers into complex parsers?
2. Is this fluent builder a bad idea or catastrophic for perf or something?

**Comment by benjamin-hodgson** [comment]
Good question! Thanks for reaching out.

First off, you can probably reduce the number of arguments you need to pass to `Map` by judiciously application of `Then`/`Before` to the parsers you don't need the results of:

```csharp
Parser<char, Person> myParser = Map(
    (name, id, title) => new Person(name, id, title),
    Name.Before(Colon.Then(SkipWhitespaces)),
    IdNumber.Before(SkipWhitespaces),
    Title
);
```

Occasionally you do need more than 8 variables though. The simplest way is to use linq:

```csharp
Parser<TToken, Person> myParser =
    from name in Name.Before(Colon.Then(SkipWhitespaces))
    from id in IdNumber.Before(SkipWhitespaces)
    from title in Title
    select new Person(name, id, title);
```

This can be slower though (basically any linq expression with more than two `from`s will produce garbage) so if you need it to be fast I would probably use `Map` and pack the intermediate results into a tuple:

```csharp
Parser<TToken, Person> myParser = Map(
    (a,b,c,def) => new Person(a, def.Item1, def.Item3),
    Name,
    Colon,
    SkipWhitespaces,
    Map(
        Tuple.Create,
        IdNumber,
        SkipWhitespaces,
        Title
    )
)
```

**Comment by AlgorithmsAreCool** [comment]
Thank you for your quick reply!

Your first code example is similar to an approach i used at first, but i found it a little awkward. 

I'll experiment with the linq syntax, but it doesn't make sense to me just yet. I need to re-watch your talk about how these things link together.

I figured the builder was against best practices, but I still might use it to build complex objects.

I'm going spend some time tonight thinking about if I can weave the parses together in a fluent way.

Thanks again!
