### ISSUE TITLE
Deconstructors for Result would be "nice to have"

### ISSUE THREAD

**Issue by mgkr** [benjamin-hodgson/Pidgin#101]
Nothing I can't do myself

```
namespace Pidgin {
  public static class ExtensionMethods {
    public static void Deconstruct<T,U>(this Result<char, (T, U)> result, out T i1, out U i2) {
      i1 = result.Success ? result.Value.Item1 : default(T);
      i2 = result.Success ? result.Value.Item2 : default(U);
    }
  }
}
```

But would be "nice to have" if there where a whole bunch of them (up to 8??) out of the box

So that you can do stuff like
`(string ws, string result) = MyParser.CallStatement.Parse(input);`

**Comment by benjamin-hodgson** [comment]
When your `result` has a tuple inside it, you can get the tuple and then use the built in tuple deconstructor.

```csharp
var (item1, item2) = result.Value;
// or, if you prefer to return default on error,
var (item1, item2) = result.GetValueOrDefault();
```

**Comment by mgkr** [comment]
Perhaps I'm doing it wrong then (not unlikely - Only just started messing around with Pidgin)
But my use case does not seem to match what you presented above.

Obviously if the result was a tuple I could use C#'s inbuild deconstructors.
But that's not what I got - But perhaps that's what I need to get?

My use case looks like this

```
    public static Parser<char, (string, string)> CallScreenStatement = Tok(
      Map((ws, csl, id) => (ws, id), WhitespaceString, CallScreenLiteral, Identifier)
    );
```

Which I then deconstruct with 

`(string ws, string result) = MyParser.CallStatement.Parse(input);`
(as shown in my first post)

I would love to know how to change my parser to get both values into the result object instead of the tuple, so I could use the inbuild deconstructors. 
Pointers would be appreciated.

**Comment by benjamin-hodgson** [comment]
`Parse` returns a `Result<char, (string, string)>` - a `Result` containing a tuple. (A `Result<TToken, T>` is an object containing either a `ParseError<TToken>` or a `T`.) All you need to do is get the tuple out of the `Result`.

<pre><code>var (ws, result) = MyParser.CallStatement.Parse(input)<b>.Value</b>;</code></pre>

If there was a parse error (and therefore no output value), `Value` will throw whereas `GetValueOrDefault` will return `default`.

**Comment by benjamin-hodgson** [comment]
`Result <TToken, T>` is just like nullable `T?`. You have to use `Value` to get at the thing inside.

**Comment by mgkr** [comment]
lol - Lightbulb moment.
Obvious once you see it :-)

Thanks!
