### ISSUE TITLE
[Question] Optional brackets parser?

### ISSUE THREAD

**Issue by mgkr** [benjamin-hodgson/Pidgin#102]
Looking for a "clever" way to parse a list that may or may not have brackets around it.
ie.
`x, y, z`
or
`[x, y, z]`

are identical (in the way that a parser should return all three (x,y,z) in both cases)

I have
```
    public static readonly Parser<char, IEnumerable<(string, BlockType, ConnectionType)>> ActionAndArgList =
      ActionAndArg
        .Between(SkipWhitespaces)
        .Separated(Comma)
        .Between(LBracket, RBracket);
```
Which works fine for the last case - But how to make it work for the first case as well?
ie. somehow make the `.Between(LBracket, RBracket)` bit optional.

I haven't had much luck playing around with the `Optional()` method...

I can of course just make a new parser as a copy of the above, just without the `.Between(LBracket, RBracket)` bit and then apply both. 
But that seems a bit "smelly" - There's got to be a "better" way?

**Comment by mgkr** [comment]
More optional...

Turns out that from the list `[x,y,z]` I'm actually only interested in `x` and `z` - I don't want `y` in my result.
In fact I don't even know what y is called/named (all list elements have the same "shape" though)

I'm sorta close(?) with something like
```
    public static readonly Parser<char, (string, BlockType, ConnectionType)> ActionAndArg = Tok(
      OneOf(
        ActionJumpArg,
        ActionCallArg
      )
      .Or(ActionAnyArg)
```
I just need to get rid of `ActionAnyArg` from my result.
If I use `.Or(ActionAnyArg.IgnoreResult())` I run into casting issues...
There is no cast from `Unit` to `(string, BlockType, ConnectionType)` - Which might be solvable, but it doesn't feel like the right way around this issue.

**Comment by benjamin-hodgson** [comment]
For the optional brackets, you can do something like this:

```csharp
CommaSeparatedList = …;
BracketedList = CommaSeparatedList.Between(LBracket, RBracket);
OptionallyBracketedList = BracketedList.Or(CommaSeparatedList);
```

(I think you might encounter some challenges distinguishing `CommaSeparatedList` from other productions in your grammar. You’ll probably need to set up your parser to backtrack if it doesn’t see the first comma or something like that.)

For the second question, if it’s always a three-element list then `Separated` won’t do the job since it parses an arbitrary length list. You can do something like `Map(X, Y, Z, (x, _, z) => (x, z))` to ignore the result of `Y`.

**Comment by mgkr** [comment]
`OptionallyBracketedList` : Nice - Thanks.
"Doesn't see the first comma" - uhoh... It won't work on a single element list?

2nd: Unfortunately an arbitrary length list. So, oh well, will just have to filter after the fact.

And thanks again for answering. I realize this is an issues list - and not a QA forum, but.... Kinda hard to find resources out there, Pidgin sadly doesn't have enough volume to make stackoverflow etc. useful.

**Comment by benjamin-hodgson** [comment]
No worries, I'm happy to give help here!

I don't know your use case, so I'm probably completely wrong, I just meant you'll need some way of knowing whether the `x` you're looking at is a regular mention of a variable `x` or a single-element list.

**Comment by mgkr** [comment]
ah yes - I see what you mean.
I thiiiink I should be OK there though. We'll see.
But thanks for the heads-up :-)
