### ISSUE TITLE
Api documentation website: Missing text - a ReadOnlySpan ref is apparently not working.

### ISSUE THREAD

**Issue by mgkr** [benjamin-hodgson/Pidgin#103]
![image](https://user-images.githubusercontent.com/7891248/117020993-3cb00400-acf7-11eb-99b1-3c3970485925.png)

It happens everywhere that `<see cref="!:ReadOnlySpan<TToken>"></see>` should be inserted (not just for [Slice](https://www.benjamin.pizza/Pidgin/v2.5.0/api/Pidgin.Parser-2.html#Pidgin_Parser_2_Slice__1_Pidgin_ReadOnlySpanFunc__0__1___0__))
Makes the text rather strange to read :-)

**Comment by benjamin-hodgson** [comment]
Thanks for pointing this out! Should be fixed on master: https://www.benjamin.pizza/Pidgin/master/Pidgin.Parser-2.html#Pidgin_Parser_2_Slice__1_Pidgin_ReadOnlySpanFunc__0__1___0__ (https://github.com/benjamin-hodgson/Pidgin/commit/c12f8e413a2443463cd73240b7e875da10815c2c)
