### ISSUE TITLE
[Question] How to flatten a double list?

### ISSUE THREAD

**Issue by mgkr** [benjamin-hodgson/Pidgin#104]
Below does not work - But is about as close as I can get.
```
ControlLiteral
  .Then(ActionAndArgList)  // <== ActionAndArgList produces an IEnumerable
  .Until(End)              // <== and now we wrap it once more for an IEnumerable of IEnumerable's
  .SelectMany              // How to flatten????
    (
      t => t.SelectMany(x => x), 
      (t,u) => u
    )
```
The objective is simple enough - To flatten a double `IEnumerable` - Which in regular C# is simply enough.
But with Pidgin there are two params for the `SelectMany` which I cant wrap my head around what they are supposed to be...

**Comment by benjamin-hodgson** [comment]
```csharp
Parser<IEnumerable<IEnumerable<T>> parser;
var flattened = parser.Select(enumerables => enumerables.SelectMany(xs => xs));
```

**Comment by mgkr** [comment]
Damn, so simple. Thanks man.

That (pidgin) `SelectMany` was a hell of a red herring then - Lead me down the wrong road.
