### ISSUE TITLE
[Question] Find all (and only) foo's and bar's

### ISSUE THREAD

**Issue by mgkr** [benjamin-hodgson/Pidgin#106]
Input: "aaa foo bbb foo ccc ddd bar eee" (location and number and order of foo and bar is random)
Result: IEnumerable consisting of two "foo"s and one "bar" (order not important - if that matters for a solution)

How to achive this?
I've played around with `SkipUntil`, `Until` and `LookAhead` but I'm stumped.

**Comment by benjamin-hodgson** [comment]
Something like

```csharp
OneOf(
    Try(foo),
    Try(bar),
    Any.ThenReturn("")  // discard the char
)
    .Many()
    .Select(xs => string.Join(" ", xs));
```

**Comment by mgkr** [comment]
Thanks! That paved the way.
FWIW - Adjusted to 
```
      public static readonly Parser<char, IEnumerable<string>> foaa =
        OneOf(
          Try(foo),
          Try(bar),
          Any.ThenReturn("")  // discard the char
        )
        .Many()
        .Select(x => x.Where(y => y != ""));
```
to fit exactly with the question (in case someone in the future looks in and wonders)

Shame that `Any.ThenReturn("") ` has to add to the enumerable - Code would look at lot better without that final filtering :-)

**Comment by mgkr** [comment]
and by the by - This can actually also work for my [2nd problem](https://github.com/benjamin-hodgson/Pidgin/issues/102#issuecomment-831946127) here as well (skipping y from a [ x, y, z] list)
