### ISSUE TITLE
[Question] How to best match anything between quotes

### ISSUE THREAD

**Issue by mgkr** [benjamin-hodgson/Pidgin#107]
Intuitively I would do
```cs
//Does not work
Any
  .ManyString()
  .Between(Quotes)
```
which doesn't work.
I think the `ManyString` is eating the end quote - and the whole thing then errors with EOF when it tries to apply the last Quotes parser.

The following seems to work
```cs
Quotes
  .Then(
     Any.ManyString()
    .Until(Quotes)
  )
```
But is that really the cleanest way of doing it? It seems... ungainly...  and also suffers from returning an `IEnumerable<string>`  - a simple `string` would be the intuitive result.

It should be possible to get `Between` to work with this somehow?

**Comment by mgkr** [comment]
Suddenly remembered `AnyCharExcept`!
```cs
AnyCharExcept("\"").ManyString()
.Between(Quotes)
```
That's not too bad I suppose.
Now just need to figure out how to something along the lines of `AnyCharExcept(Quotes)` to make it real pretty

**Comment by benjamin-hodgson** [comment]
Glad to know you figured it out! 🙂
