### ISSUE TITLE
[Question] How to properly skip comments

### ISSUE THREAD

**Issue by BalassaMarton** [benjamin-hodgson/Pidgin#110]
I'm having a hard time understanding how the `CommentParser` should be used. Suppose I have a C-like language with block and line comments. Can I somehow 'globally' ignore comments in the parser?

**Comment by benjamin-hodgson** [comment]
[SkipBlockComment](https://www.benjamin.pizza/Pidgin/v2.5.0/api/Pidgin.Comment.CommentParser.html#Pidgin_Comment_CommentParser_SkipBlockComment__2_Pidgin_Parser_System_Char___0__Pidgin_Parser_System_Char___1__) produces a `Parser` which recognises the start of a block comment and skips everything until the end of the block comment. So to skip all block comments in a file, you can treat them the same as you treat whitespace:

```csharp
Parser<char, Unit> SkipWhitespaceAndComments =
    SkipBlockComment(...)
    .Or(Whitespace.IgnoreResult())
    .SkipMany();
```

You can then use `SkipWhitespaceAndComments` eg after every token.

**Comment by BalassaMarton** [comment]
Thanks, after a day of trial and error, I did something like that. What wasn't so obvious for me is that `String` will consume characters before failing, so it must be wrapped with `Try` every time it is used for lookahead. Awesome library btw :)
