### ISSUE TITLE
Documentation for using ExpressionParser

### ISSUE THREAD

**Issue by hswami** [benjamin-hodgson/Pidgin#113]
I am trying to figure out how to use the ExpressionParser but the only thing by way of documentation is a unit test. Can something a little more helpful be provided?

**Comment by benjamin-hodgson** [comment]
Yeah, I (or a contributor!) should probably write some thorough documentation for the `ExpressionParser`. There is [an example](https://github.com/benjamin-hodgson/Pidgin/blob/main/Pidgin.Examples/Expression/ExprParser.cs) in the repo but it's not explained in detail.

**Comment by hswami** [comment]
> Yeah, I (or a contributor!) should probably write some thorough documentation for the `ExpressionParser`. There is [an example](https://github.com/benjamin-hodgson/Pidgin/blob/main/Pidgin.Examples/Expression/ExprParser.cs) in the repo but it's not explained in detail.

I can take a first stab at it and you can review.

On an unrelated note, I was able to put together a parser for Excel formulas, including cell ranges and cross-worksheet references. Pidgin made it possible, and with your permission I'd like to add it to the examples project as well. That way can review that as well and provide feedback if/when you have the time.

**Comment by benjamin-hodgson** [comment]
Sounds good! Thanks!

**Comment by benjamin-hodgson** [comment]
Added an example (doctested) to [the API docs](https://www.benjamin.pizza/Pidgin/v3.2.0/Pidgin.Expression.ExpressionParser.html#Pidgin_Expression_ExpressionParser). Thanks for your interest!
