### ISSUE TITLE
Position of the match

### ISSUE THREAD

**Issue by RomanSoloweow** [benjamin-hodgson/Pidgin#115]
Can I find out the position where the match was found?

**Comment by benjamin-hodgson** [comment]
[`CurrentOffset`](https://www.benjamin.pizza/Pidgin/v2.5.0/api/Pidgin.Parser-1.html#Pidgin_Parser_1_CurrentOffset) or [`CurrentPos`](https://www.benjamin.pizza/Pidgin/v2.5.0/api/Pidgin.Parser-1.html#Pidgin_Parser_1_CurrentPos), depending what exactly you need.
