### ISSUE TITLE
An example of parsing a mathematical expression

### ISSUE THREAD

**Issue by RomanSoloweow** [benjamin-hodgson/Pidgin#116]
I'm trying to get started with Pidgin, but it's hard without examples. I think the presence of an example of parsing a mathematical expression will lower the entry threshold for inexperienced users

**Comment by benjamin-hodgson** [comment]
https://github.com/benjamin-hodgson/Pidgin/blob/main/Pidgin.Examples/Expression/ExprParser.cs
