### ISSUE TITLE
What is the right approach to parse Enums?

### ISSUE THREAD

**Issue by YarekTyshchenko** [benjamin-hodgson/Pidgin#117]
Since `ParseException` is private, this approach has issues:
```csharp
public enum ExampleEnum
{
    One,
    Two,
}

var enumParser = Any.ManyString().Select(Enum.Parse<ExampleEnum>);
```

Enum parse throws various exceptions which Select doesn't convert back to ParseException.

Another way to create an enum parser would be to get a list of all valid enums as strings, and then Or them together, but that seems somehow wrong.

```csharp
        private static Parser<char, T> ParseEnum<T>()
            where T : struct, Enum
            =>
                OneOf(Enum.GetNames<T>()
                        .Select(String)
                        .Select(Try)
                        .ToArray())
                    .Select(Enum.Parse<T>);

```
Edit: Updated the enum parser code that we ended up using.

What are you throughts?

**Comment by benjamin-hodgson** [comment]
I wouldn't try to do that sort of semantic-level analysis in the parser. Parse a number and then check whether it's prime later

**Comment by YarekTyshchenko** [comment]
That is obviously contrived example. IMO it does belong in a parser, because it may be combined with other parsers, using `OR`. Currently we solve it by creating a parser from all the possible enums, but I'm not fussed about performance of it yet. Anyway, it felt strange that the exception wasn't public, and there was no way of wrapping a function to turn it into a parser building block.

**Comment by benjamin-hodgson** [comment]
I'm unclear on what the ask is here. Your `ParseEnum` method looks like the right way to do it, and I'd be happy to accept it as a contribution to ship with the library. Is there a different outcome you'd prefer?

**Comment by YarekTyshchenko** [comment]
I'd prefer for `Select` to rethrow exception as ParseException

**Comment by benjamin-hodgson** [comment]
> I'd prefer for Select to rethrow exception as ParseException

That's a breaking change. You can code it up yourself fairly easily:

```csharp
public static Parser<TToken, U> SelectCatch<TToken, T, U>(this Parser<TToken, T> p, Func<T, U> f)
    => p.SelectMany(x =>
    {
        try
        {
            return Return(f(x));
        }
        catch (Exception e)
        {
            return Fail<U>(e.Message);
        }
    });
```

**Comment by YarekTyshchenko** [comment]
Thats exactly what I'm looking for. I didn't realise `Return` and `Fail` where exposed already. Thanks!

**Comment by benjamin-hodgson** [comment]
Cool, happy to help!
