### ISSUE TITLE
Correct handling of EOL of EOF

### ISSUE THREAD

**Issue by voidmain02** [benjamin-hodgson/Pidgin#118]
Hello!

Imagine that we need to parse a string with digits separated by line brakes. I have these parsers:

```csharp
private static readonly Parser<char, Unit> LineTerminator = Try(EndOfLine).IgnoreResult().Or(End);

private static readonly Parser<char, string> Line = Digit.Until(LineTerminator).Select(string.Concat);

private static readonly Parser<char, IEnumerable<string>> Lines = Line.Many();
```

And I unexpectedly get "Many() used with a parser which consumed no input" error when call `Lines.ParseOrThrow("123\n456")`.

In our fictional scenario we can use `SeparatedAndOptionallyTerminated(LineTerminator)`. And it works as expected. But unfortunately, this approach isn't suitable in my real scenario. Is it possible to solve my task having the `Line` parser with the line terminator at the end?

Interestingly, almost the same code works well with Sprache:
```csharp
private static readonly Parser<string> Line =
    from line in Parse.Digit.Many().Text()
    from terminator in Parse.LineTerminator
    select line;

private static readonly Parser<IEnumerable<string>> Lines = Line.Many();
```

I'd appreciate any help. Thank you!

**Comment by benjamin-hodgson** [comment]
`End` doesn't consume input when it succeeds. I'm unclear on why you don't want to use `SeparatedAndOptionallyTerminated` in your situation, it seems like exactly the right choice for the question as written. Can you provide some more context?

**Comment by benjamin-hodgson** [comment]
Oh, I bet this would work if you used `Digit.AtLeastOnceUntil` instead of `Digit.Until`
