### ISSUE TITLE
Many? - question

### ISSUE THREAD

**Issue by n9** [benjamin-hodgson/Pidgin#12]
Let's have the following (simplified) example:
```C#
static readonly Parser<char, IEnumerable<string>> Foo = OneOf(Map(c => "<>", Token('|')), Token(c => c != '|').ManyString()).Many();

void Main()
{
	Foo.Parse("|bar|foo").Dump();
}
```

It fails with `Many() used with a parser which consumed no input`. What's wrong with that?

**Comment by benjamin-hodgson** [comment]
`p.ManyString()` can consume no input (if `p` fails immediately). So `p.ManyString().Many()` will loop without making progress. Without knowing what you’re trying to do it’s hard to recommend a fix but you might want `AtLeastOnceString()`

**Comment by benjamin-hodgson** [comment]
You might try parsing your `|foo|bar` example using `SeparatedBy`

**Comment by n9** [comment]
Thank you for your answers. I missed that `ManyString()` might not read anything.  I am trying to write a simple parser for (a bit extraordinary) markup language. First, I checked your `XmlParser` example, however it seems to me that it cannot parse text nodes.

**Comment by benjamin-hodgson** [comment]
Ya I didn’t implement text nodes in the example. I’d be very happy to accept a PR!
