### ISSUE TITLE
Parsing an identifier / scopes

### ISSUE THREAD

**Issue by Azurelol** [benjamin-hodgson/Pidgin#120]
Hello,

I am trying to write some functions to parse identifiers and scopes, and struggling to do so (I went over the examples).

Given these test cases:

```csharp
        [TestCase(" bob", "bob")]
        [TestCase(" bob ", "bob")]
        [TestCase("bob ", "bob")]
        [TestCase("pipeline ", "pipeline")]
        [TestCase("pipeline {}", "pipeline")]
        [TestCase("stage('ios')", "stage('ios')")]
        [TestCase("stage(\"android\") ", "stage(\"android\")")]
        [TestCase(@"
bob ", "bob")]
        public void ParsesIdentifier(string input, string expected) { ... }


        [TestCase("{}")]
        [TestCase("{} ")]
        [TestCase(" {}")]
        [TestCase(" {cat}")]
        [TestCase("{ }")]
        [TestCase(" { } ")]
        [TestCase("{ }")]
        [TestCase("{ hello } ")]
        [TestCase(@"{ 
} ")]
        [TestCase(@"{ 
    cats
} ")]
        public void ParsesScope(string input) { .. }
```

What would be the correct way to parse these? My current implementations looks like so:

```csharp
        public static readonly Parser<char, string> Identifier = Any.Until(Try(End))
            .Select(c => System.String.Concat(c))
            .Labelled("Identifier");

        public static readonly Parser<char, string> Scope = AnyCharExcept('{', '}')
                .ManyString()
                .Between(LBrace, RBrace)
                .Between(SkipWhitespaces)
                .Labelled("Scope");

        public static readonly Parser<char, Block> Block = Map((name, scope) => new Block(name, scope), Identifier, Scope);
```

The scope one seems to work, but the identifier one fails.  I will also need the scoping one to be able recurse properly soon,
which I haven't gotten to yet.

My goal is to be able to parse blocks recursively, where a `Block` is:

```csharp
    public class Block
    {
        public string name { get; }
        public string text { get; }
        public Block[] blocks { get; }
        public Block(string name, string text)
        {
            this.name = name;
            this.text = text;
        }
    }
```

```
a {
 b {   
 }
  c { ...}
  d { 
   ...
  }
}
```

**Comment by RomanSoloweow** [comment]
@Azurelol any news about it?

**Comment by benjamin-hodgson** [comment]
As written, your `Identifier` parser will always consume+return the entire input - whitespace, symbols, and all - because `Any` matches **any character**. I suspect you really want something like `Letter.ManyString()`, but it depends on your grammar. (Many languages allow numbers in identifiers but not as the first letter, for example.)

[The whitespace-handling kit I outlined on my website](https://www.benjamin.pizza/posts/2019-12-08-parsing-prolog-with-pidgin.html#handling-tokens-and-whitespace) might come in useful too.

Hope this helps!

**Comment by Azurelol** [comment]
Thank you for your response! I apologize for my late reply. My work on a feature that would be using this has been postponed so I haven't had time to get back to it.

I will give what you suggested a try.
