### ISSUE TITLE
How to implement lazy matching?

### ISSUE THREAD

**Issue by RomanSoloweow** [benjamin-hodgson/Pidgin#123]
How to implement lazy matching to get regex-like behavior.

![image](https://user-images.githubusercontent.com/29205560/155859612-d26aa917-b28d-499b-9a20-f13ef22afc30.png)

**Comment by benjamin-hodgson** [comment]
```
String("return ")
    .Then(AnyCharExcept(';').ManyString())
    .Before(Char(';'))
```

seems like it’d do what you specified. Seems like there could be an [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem) here though - what about inputs like `return ';';`?
