### ISSUE TITLE
Lazy matching without lookahead

### ISSUE THREAD

**Issue by RomanSoloweow** [benjamin-hodgson/Pidgin#124]
I'm sorry, I guess I didn't phrase my question correctly #123.

My task is to implement matching on the principle of " as many times as possible".

Example: any characters that may be between return and ; 

This can be described with a placeholder pattern "return $value$;"
Those. in place of $value$ there can be any characters, including many times ";". You need to somehow get a match of the largest possible length.

![image](https://user-images.githubusercontent.com/29205560/155861197-924a14bf-871f-4353-a30a-1b104cfcda79.png)

A solution with only a lookahead comes to my mind, it doesn't seem right to me. Because example with ";" is conditional and can be replaced by more complex parsers.

**Comment by RomanSoloweow** [comment]
In general, my solution looks like this:

```C#
var nextParser = Char(';');

var parser = String("return ").Then(Any.AtLeastOnceUntil(
      Lookahead(nextParser.Then(End).Try())
).AsString());
```

But again, using Lookahead doesn't seem like a good option to me and I hope there are other ways

**Comment by RomanSoloweow** [comment]
If we need to continue parsing, then the solution will be even uglier

```C#
var nextParser = Char(';');
var nextNextParser =; //other parser here

var parser = String("return ").Then(Any.AtLeastOnceUntil(
    Lookahead(nextParser.Then(nextNextParser))
).AsString());
```

**Comment by RomanSoloweow** [comment]
@benjamin-hodgson  any ideas?

**Comment by benjamin-hodgson** [comment]
I think the behaviour you've described is quite unlikely to be desirable. What about inputs like `return foo; return bar;`?

**Comment by RomanSoloweow** [comment]
This case will also be processed. But my solution isn't productive.
