### ISSUE TITLE
Getting current position in 3.x

### ISSUE THREAD

**Issue by atrauzzi** [benjamin-hodgson/Pidgin#127]
I noticed that the 2.x versions have `CurrentPos` as a way to get the current position.  Does a similar facility exist in 3.x?

**Comment by atrauzzi** [comment]
Also seeing that `CurrentPos` is internal right now.  Is this my best option for the time being?

```c#
public class Position : Parser<char, int>
{
    public override bool TryParse(ref ParseState<char> state, ref PooledList<Expected<char>> expecteds, out int result)
    {
        result = state.Location;

        return true;
    }
}
```

**Comment by benjamin-hodgson** [comment]
It’s still public! https://github.com/benjamin-hodgson/Pidgin/blob/main/Pidgin/Parser.CurrentPos.cs#L16

**Comment by atrauzzi** [comment]
Ah I see, I needed to import `using static Pidgin.Parser<char>;`

That being said, it still doesn't seem to be reporting the positions I'm hoping to get.  By any chance could you spot - at a glance - a smell in the following:

```csharp
public static Parser<char, Declaration> Snippet => Parser.Map(
        (start, identifier, end) => new Declaration(
            start.Col,
            end.Col,
            identifier,
            new Collection<Behaviour>()
        ),
        CurrentPos,
        Open.Then(Parser
            .Try(IdentifierWithGroup)
            .Cast<Identifier>()
            .Or(Identifier)),
        Close.Then(CurrentPos)
    );
```

What appears to be happening is that it's reporting back the correct start position for my very first `start`, but then the position of the `end` and any subsequent `start` and `end` values for repeated matches are off by four or more.

**Comment by atrauzzi** [comment]
Ah perfect, I just needed to do `using static Pidgin.Parser<char>;`

Thank you!  This library is incredible.

**Comment by benjamin-hodgson** [comment]
Thanks! ❤️
