### ISSUE TITLE
SourcePosDelta => MatchPos

### ISSUE THREAD

**Issue by RomanSoloweow** [benjamin-hodgson/Pidgin#131]
Hi,
recently, I needed to have complete information about the result of the parser: StartLine, EndLine, StartColumn, EndColumnt, StartOffset, EndOffset, Lenght.

I could get the result in the way shown in the screenshot, but that doesn't seem like an elegant solution to me. This will require some minor internal changes, but I think you could implement it out of the box.

![image](https://user-images.githubusercontent.com/29205560/164838707-b96dec13-7b33-42c5-8eeb-a8c6f1ba964f.png)

**Comment by benjamin-hodgson** [comment]
What you have there looks sensible to me. If you want to improve the code you could wrap the pair of `CurrentPos` and `CurrentOffset` into something reusable,

```csharp
Parser<TToken, (int, SourcePos)> FullPositionInfo { get; }
    = Map(
        ValueTuple.Create,
        CurrentOffset, CurrentPos
    );
```

It’s a fairly straightforward usage of the library, so I don’t think we _need_ to add any special support to the API, but in general I’m not against adding convenience methods such as `FullPositionInfo` so I’d accept a PR!
