### ISSUE TITLE
Question: can this URN parser be improved?

### ISSUE THREAD

**Issue by egil** [benjamin-hodgson/Pidgin#133]
Hi, awesome project! I am trying to learn how to use Pidgin and its syntax, and I think what I have so far in my URN parser is not optimum, but could be wrong. Either way, would love some feedback.

The [syntax for an URN](https://en.wikipedia.org/wiki/Uniform_Resource_Name#Syntax) can be found on WIKI. The relevant parts for the parser is in the code below though.

```c#
/// <summary>
/// A parser that parses and returns a single alpha character case insensitive.
/// </summary>
/// <remarks>
/// A-Z / a-z
/// </remarks>
private static Parser<char, char> Alpha { get; }
    = CIOneOf('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z');

/// <summary>
/// A parser that parses and returns a single alpha numerical character case insensitive.
/// </summary>
/// <remarks>
/// A-Z / a-z / 0-9
/// </remarks>
private static Parser<char, char> AlphaNum { get; }
    = OneOf(Alpha, Digit);

/// <remarks>
/// DIGIT / "A" / "B" / "C" / "D" / "E" / "F"
/// </remarks>
private static Parser<char, char> HexDig { get; }
    = OneOf(Digit).Or(OneOf('A', 'B', 'C', 'D', 'E', 'F'));

/// <remarks>
/// pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
/// pct-encoded   = "%" HEXDIG HEXDIG
/// unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
/// sub-delims    = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
///
/// alphanum      = ALPHA / DIGIT
/// </remarks>
private static Parser<char, string> PChar { get; }
    = OneOf(
        OneOf(AlphaNum, Char('-'), Char('.'), Char('_'), Char('~')).AtLeastOnceString(),   // unreserved
        Map((x, y) => x + y, Map((x, y) => $"{x}{y}", Char('%'), HexDig), HexDig),                  // pct-encoded
        OneOf('!', '$', '&', '\'', '(', ')', '*', '+', ',', ';', '=').AtLeastOnceString(), // sub-delims
        OneOf(':', '@').AtLeastOnceString());

/// <summary>
/// A URN parser. Note, only supports <c>assigned-name</c> form,
/// i.e. does not include support for <c>rq-components</c> and 
/// <c>"#" f-component</c>.
/// </summary>
/// <remarks>
/// <code>
/// namestring    = assigned-name
///                 [ rq-components ]
///                 [ "#" f-component ]
/// assigned-name = "urn" ":" NID ":" NSS
/// NID           = (alphanum) 0*30(ldh) (alphanum)
/// ldh           = alphanum / "-"
/// NSS           = pchar *(pchar / "/")
/// rq-components = [ "?+" r-component ]
///                 [ "?=" q-component ]
/// r-component   = pchar *( pchar / "/" / "?" )
/// q-component   = pchar *( pchar / "/" / "?" )
/// f-component   = fragment
/// </code>
/// </remarks>
public static Parser<char, string> Urn { get; }
    = (from urn in CIString("urn")
       from urnColon in Char(':')
       from nidStart in AlphaNum
       from ldhAndNidEnd in OneOf(AlphaNum, Char('-'))
                                .ManyString()
                                .Where(x => x.Length < 31 && x.Length > 0 && x[^1] != '-')
       from nidColon in Char(':')
       from nesStart in PChar
       from nesRest in OneOf(PChar, Char('/').AtLeastOnceString()).ManyString()
       select urn + urnColon + nidStart + ldhAndNidEnd + nidColon + nesStart + nesRest).Labelled("URN");
```

There are a few things here I think could be done differently, but don't know how:

1. `PChar` parser could perhaps be `Parser<char, char>` if its possible to somehow tell Pidgin to look for the `pct-encoded` but return them as chars. That would mean that the `nesRest` part of the `Urn` parser can be simplified.
2. The `NID` portion of the `Urn` parser says that it should start with an `alphanum` char, the 0-30 alphanum or '/' chars, and then a `alphanum` char. It would be nice if I could express the NID start, LDH, and NID end separately, but could not figure it out.

Some tests, that all pass:

```c#
[Theory]
[InlineData("urn:aa:y")]
[InlineData("urn:aa:%22")]
[InlineData("urn:isbn:0451450523")]
[InlineData("urn:isan:0000-0000-2CEA-0000-1-0000-0000-Y")]
[InlineData("urn:ISSN:0167-6423")]
[InlineData("urn:ietf:rfc:2648")]
[InlineData("urn:ietf:params:scim:schemas:extension:enterprise:2.0:User")]
public void UrnParser_success(string input)
{
    var result = Urn.Parse(input);
    result.Success.Should().BeTrue("parser can parse '{0}'", input);
    result.Value.Should().Be(input);
}

[Theory]
[InlineData("foo")]
[InlineData("urn:a:yy")]
[InlineData("urn:a-:yy")]
[InlineData("urn:aa:\"")]
public void UrnParser_failure(string input)
{
    var result = Urn.Parse(input);
    result.Success.Should().BeFalse();
}
```

Appreciate any input or suggestions, thanks!

Regards, the parser newbie ;)

**Comment by benjamin-hodgson** [comment]
Thanks for the interest! I had a quick look over your code and I have a few minor suggestions:

* `Alpha` and `AlphaNum` are in the box: https://www.benjamin.pizza/Pidgin/v3.1.0/Pidgin.Parser.html#Pidgin_Parser_Letter
* The `// pct-encoded` line could be flattened: `Map((pct, a, b) => pct + a + b, Char('%'), HexDig, HexDig)`
* Is `pct-encoded` intended to return the decoded character or do you want the literal input? (Should `%20` be read as `"%20"` or as `" "`? If the latter, you'll need to modify the func you pass to `Map` to make it interpret the two-digit escape code.)
* You could factor the `AtLeastOnceString` out of the branches of `PChar` and simplify the handling of individual characters:
    ```
    PChar = AlphaNum
        .Or(OneOf(
            '-', '.', '_', '~',  // unreserved
            '!', '$', '&', '\'', '(', ')', '*', '+', ',', ';', '=',  // pct-encoded
            ':', '@'
        ))
        .Map(x => x.ToString())
        .Or(
            Map((pct, a, b) => pct + a + b, Char('%'), HexDig, HexDig)
        )
        .AtLeastOnceString();
   ```

**Comment by egil** [comment]
Thanks for the feedback.

> * `Alpha` and `AlphaNum` are in the box: https://www.benjamin.pizza/Pidgin/v3.1.0/Pidgin.Parser.html#Pidgin_Parser_Letter

I remember looking at the `Letter` parser, and IIRC it also include other characters besides `a-zA-Z`, e.g. `ØÆÅ`, that's why I created my own that only include the English language letters.

> * The `// pct-encoded` line could be flattened: `Map((pct, a, b) => pct + a + b, Char('%'), HexDig, HexDig)`
> * Is `pct-encoded` intended to return the decoded character or do you want the literal input? (Should `%20` be read as `"%20"` or as `" "`? If the latter, you'll need to modify the func you pass to `Map` to make it interpret the two-digit escape code.)

Excellent point. I probably want that, yes.

`Map((_, a, b) => (char)Convert.ToUInt32($"{a}{b}", fromBase: 16), Char('%'), HexDig, HexDig)` seem to do the trick. It also means 
PChar becomes a `Parser<char, char>`, which simplifies the code down stream. I.e.:

```c#
private static Parser<char, char> PChar { get; }
    = OneOf(
        AlphaNum, // unreserved
        OneOf('-', '.', '_', '~', // unreserved
              '!', '$', '&', '\'', '(', ')', '*', '+', ',', ';', '=', // sub-delims
              ':', '@'), 
        Map((_, a, b) => (char)Convert.ToUInt32($"{a}{b}", fromBase: 16), Char('%'), HexDig, HexDig)); // pct-encoded
```

Thanks again.
