### ISSUE TITLE
Is there a good way to turn Digit.Repeat(n) into a string?

### ISSUE THREAD

**Issue by atrauzzi** [benjamin-hodgson/Pidgin#137]
Right now it seems to return `IEnumerable<char>`, which is obviously a precursor to a string.  I was wondering if Pidgin had any handy way of doing this, versus me just manually making the string in a `Map` somewhere later on?

**Comment by benjamin-hodgson** [comment]
Does this do what you meant?

```csharp
static Parser<TToken, string> RepeatString<TToken>(this Parser<TToken, char> p, int n)
    => p.Repeat(n).Select(string.Concat);
```

**Comment by atrauzzi** [comment]
It's cleaner, yes :slightly_smiling_face:
