### ISSUE TITLE
Matching an exact string

### ISSUE THREAD

**Issue by Pyth0ff** [benjamin-hodgson/Pidgin#142]
I'm currently trying to understand the library a little bit more and I struggle to match an exact words, e.g. 'ON' and 'OFF'. I just want the word 'ON' and not for example 'ONLY'. How can I achieve that after the word only whitespace or eol is allowed?

```
var p = Try(String("ON").Or(String("OFF"))).Before(SkipWhitespaces);
p.ParseOrThrow("ON");
p.ParseOrThrow("ON ");
p.ParseOrThrow("OFF");
p.ParseOrThrow("ONLY"); // Should fail
```

Can interpret the first line as follow? "Try to read ON or either OFF before skipping any whitespace afterwards."
Means leading whitespace `p.ParseOrThrow("   ON");` would already fail?

I hope someone can explain me the mistake I'm doing right now.

**Comment by benjamin-hodgson** [comment]
How about `.Before(Whitespace.SkipAtLeastOnce())`? You can throw a `.Or(End)` in there if you need to parse a token right at the end of the input.
