### ISSUE TITLE
Parsing double

### ISSUE THREAD

**Issue by pjpatricio** [benjamin-hodgson/Pidgin#15]
Hi, Thanks for such a great library, I noticed you have  both DecimalNum and Num returning the same int type. is this a "copy paste feature"?

Is there any Parser to parse a decimal number and return a double? 

I am trying to parse a sequence of numbers like below:
114365.0 121429.0 6.2 4.0 30357.0 117165.0

Fine if you don't, I will write a new one, but as you have created the DecimalNum thought would be worth to ask you this question.

        //
        // Summary:
        //     A parser which parses a base-10 integer with an optional sign. The resulting
        //     int is not checked for overflow.
        //
        // Returns:
        //     A parser which parses a base-10 integer with an optional sign
        public static Parser<char, int> DecimalNum { get; }

        //
        // Summary:
        //     A parser which parses a base-10 integer with an optional sign. The resulting
        //     int is not checked for overflow.
        //
        // Returns:
        //     A parser which parses a base-10 integer with an optional sign
        public static Parser<char, int> Num { get; }

Thanks in Advance,
Paulo.

**Comment by benjamin-hodgson** [comment]
Thanks for getting in touch. The word "Decimal" in `DecimalNum` refers to the fact that it parses numbers in base 10 (as opposed to "octal" and "hexadecimal"). I would definitely accept a pull request adding some basic parsers for decimal floating point numbers.

**Comment by pjpatricio** [comment]
Nice one, I will look after this one so! Thank you.

**Comment by pjpatricio** [comment]
I have only Visual Studio 2015... any workarounds for me to open the solution please?

**Comment by benjamin-hodgson** [comment]
@pjpatricio What problems/error messages are you encountering? I usually work in VSCode but if it doesn't work in VS I've done something wrong!

**Comment by benjamin-hodgson** [comment]
FWIW it builds ok in VS2017 on my Windows VM

**Comment by pjpatricio** [comment]
Thanks for letting me know @benjamin-hodgson .

I am having an error related with conflicts between different versions of "System.ValueTuple" when I compile the solution in VSCode, this happens because of the FParsec project.

**Comment by pjpatricio** [comment]
I removed the FParsec and Bench Projects from my solution to workaround the issue, and focus on the task in hand of implementing the floating point parser for the moment, I will keep you posted regarding  my progress.

**Comment by benjamin-hodgson** [comment]
I get that warning too (I've tried to fix it but it just causes more versioning conflicts), but I think it's just a warning and not an error. It shouldn't prevent you from building the solution.

**Comment by pjpatricio** [comment]
Thanks @benjamin-hodgson I have implemented an initial version of the floating point and will prepare a pull request in the next few days!

**Comment by benjamin-hodgson** [comment]
Sounds great! Looking forward to reviewing it

**Comment by mustik22** [comment]
I have an initial working version of a floating point primitive.

Examples (test script):
'1.1' = 1.1 ... ok
'12.12' = 12.12 ... ok
'123.123' = 123.123 ... ok
'123.+.123' =  123.123 ... ok
'PI:=3.14159265359' = 3.14159265359 ... ok
'INT(PI)' = 3 ... ok
'ROUND(PI,1)' = 3.1 ... ok
'ROUND(PI,2)' = 3.14 ... ok
'ROUND(PI,3)' = 3.142 ... ok

Usage:

New parser
private static readonly Parser<char, IExpr> LiteralFloat
  = Tok(Float)
        .Select<IExpr>(value => new Literal(value))
        .Labelled("float literal");

Builder:
private static Parser<char, IExpr> BuildExpressionParser()
        {
            Parser<char, IExpr> expr = null;

            var term = OneOf(
                Identifier,
                LiteralFloat,
                LiteralString,
                Literal,
                Parenthesised(Rec(() => expr)).Labelled("parenthesised expression")
            );
...

The change was a bit complex and It requires that numeric expressions be re-parsed (if INT is desired).  I am not sure if there was an easier method (or one more in line with the philosophy of the engine), would love to discuss.

**Comment by mustik22** [comment]
I can either send you a synopsis of the code and you can integrate it or you could approve a pull request.  I recommend three areas of change ...

1) Update the users Literal designation from int to object.  This allows the literals to contain integers, doubles, strings, booleans etc.

2) Add a new floating point core parser

3) Add a new method of multi-step accumulation and result processing

I hope this will be a useful addition to this excellent product.

**Comment by benjamin-hodgson** [comment]
I'd be very happy to look at what you have in a pull request. Thanks!

**Comment by mustik22** [comment]
Is there any permission needed to create a branch to reference in the pull request?

**Comment by mustik22** [comment]
<img width="997" alt="image" src="https://user-images.githubusercontent.com/27729947/49889042-876f0f80-fe0e-11e8-8217-08b016caddd8.png">

**Comment by hansmbakker** [comment]
@mustik22 Do you have any update on this?

**Comment by hansmbakker** [comment]
Turns out that this is tracked in #23.

**Comment by benjamin-hodgson** [comment]
Apologies for the confusion. I've renamed #23 to clarify its purpose

**Comment by davidaramant** [comment]
Are you guys gonna pick this up again soon? :)

I'm parsing a format with a lot of floats in them and the parser from the pull request is probably faster than what I'm doing.

**Comment by benjamin-hodgson** [comment]
Thanks for your interest @davidaramant! I haven't had the time to work on it recently but I would be very happy to accept a contribution!

**Comment by benjamin-hodgson** [comment]
Merged in #23 and shipped in [v2.2.0](https://www.nuget.org/packages/Pidgin/2.2.0)
