### ISSUE TITLE
Should `DecimalNum` return `decimal` instead of `int`?

### ISSUE THREAD

**Issue by Odonno** [benjamin-hodgson/Pidgin#154]
I noticed that `DecimalNum` is used for integer discovery. Is it intended? Should it not return a `decimal` like expected? Maybe by creating a `IntegerNum` parser if there isn't any for `int` discovery.

**Comment by benjamin-hodgson** [comment]
"Decimal" means "base ten".

**Comment by Odonno** [comment]
I see. Still feel a little confusing.

Thank you for your answer Benjamin.
