### ISSUE TITLE
Add cast operator to Maybe<T> and Result<T>?

### ISSUE THREAD

**Issue by znakeeye** [benjamin-hodgson/Pidgin#157]
Just an idea. Wouldn't it make sense to add a cast operator to `Maybe<T>`? And perhaps also `Result<T>`.

E.g.:
```c#
public static implicit operator T(Maybe<T> maybe) => maybe.GetValueOrDefault();
```
Often I end up with an `Optional()` where I want my token to be a nullable instance. If `Maybe<T>` had the above cast operator, there would be no need to "bloat" the parser with a bunch of `GetValueOrDefault()` calls.

**Comment by benjamin-hodgson** [comment]
I'm strongly against adding an implicit cast. `Maybe` makes you **decide** what to do with a missing value, an implicit cast makes it way too easy to forget. You could accidentally invoke the implicit cast by churning code elsewhere.

I'm open in principle to adding an explicit (`(T)`) cast, but it's not obvious to me what it should do. `GetValueOrDefault` is an option, but I think `.Value` is a better match for the way casts usually work (cf `Nullable`'s casting behaviour).

Either way I don't think `(Foo)result` is really any more readable than `result.Value` so I don't think such an API would really pay its way.

If you're finding the `GetValueOrDefault()` calls repetitious, you could just write a method:

```csharp
static Parser<T> OptionalOrDefault(this Parser<T> p)
    => p.Optional().Map(m => m.GetValueOrDefault());
```

**Comment by znakeeye** [comment]
I agree. The extension method is great. Thanks.
