### ISSUE TITLE
Update build to netstandard2.0

### ISSUE THREAD

**Issue by Herdubreid** [benjamin-hodgson/Pidgin#16]
I'm experimenting with your parser (Celin.AIS.Data) but got stuck by a bulk of 'is defined in an assembly that is not referenced...' errors.  After hours of googling and trial and errors I finally pulled the Pidgin source and saw that its target is netstandard1.3.  After building it with netstandard2.0 as the target, so it matches my library, the errors dissipated.

**Comment by benjamin-hodgson** [comment]
What target framework are you using to compile your dependent library?

**Comment by Herdubreid** [comment]
.NET Standard 2.0

**Comment by benjamin-hodgson** [comment]
That's *supposed* to work out of the box. netstandard13 is a subset of netstandard20. I can add an extra compile target, I guess, but it's quite annoying that the Core tooling isn't doing the right thing.

**Comment by jmlane** [comment]
Aside in support of adding a `netstandard2.0` target, from https://docs.microsoft.com/en-us/dotnet/standard/net-standard#which-net-standard-version-to-target:
> [...]targeting lower .NET Standard versions introduces a number of support dependencies. If your project targets .NET Standard 1.x, we recommend that you also target .NET Standard 2.0. This simplifies the dependency graph for users of your library that run on .NET Standard 2.0 compatible frameworks, and it reduces the number of packages they need to download.

**Comment by Herdubreid** [comment]
Replacing `netstandard1.3` with `netstandard2.0` in Pidgin.csprj is simple enough, and works fine for me.

**Comment by benjamin-hodgson** [comment]
That'd be a backwards-incompatible change. I just need to _add_ a `netstandard2.0` target (not replace the existing one).

**Comment by Herdubreid** [comment]
I meant it's an easy change for me to make, i.e. the user.

**Comment by benjamin-hodgson** [comment]
https://github.com/benjamin-hodgson/Pidgin/commit/fb7b862cb37a5fd700b6a7ff85d687cb3430177b

**Comment by Herdubreid** [comment]
I just published my [aisDataBrowser](https://herdubreid.github.io/aisDataBrowser/) with the parser from  [Celin.AIS.Data](https://github.com/Herdubreid/Celin.AIS.Data)

I still got some distance to go with this, for example on parsing error messages, but so far it's promising.

I'm particularly impressed by the 'primitive approach' of Pidgin.  Construct a complex parser from a combination of simple parser -- the Lego approach!
