### ISSUE TITLE
Make `CurrentOffset` long type?

### ISSUE THREAD

**Issue by wakuflair** [benjamin-hodgson/Pidgin#161]
https://github.com/benjamin-hodgson/Pidgin/blob/08fde6d183dccf4d0b326ef8e5ba4076d5a57593/Pidgin/Parser.CurrentOffset.cs#L8

Hi @benjamin-hodgson 
I'd like to use a long type `CurrentOffset`, as for large binary data, `int` may not be enough.

**Comment by benjamin-hodgson** [comment]
Great point, I obviously wasn't thinking and just defaulted to `int`. I'll have to make it a new API (ie `CurrentOffsetLong` or similar) so as not to break existing usages - any input on the naming?

**Comment by benjamin-hodgson** [comment]
Shipped in 3.3.0 https://www.nuget.org/packages/Pidgin/3.3.0
