### ISSUE TITLE
Performance issue in ExpressionParser.Build

### ISSUE THREAD

**Issue by mustik22** [benjamin-hodgson/Pidgin#17]
We are trying to build an expression parser using Pidgin, based on the provided example code.  I have two questions:

1) Using the following build

 expr = ExpressionParser.Build(
                term,
                new[]
                {
                    Operator.PostfixChainable(call),
                    Operator.Prefix(Neg).And(Operator.Prefix(Complement)).And(Operator.Prefix(UPlus)),
                    Operator.InfixL(Multiply).And(Operator.InfixL(Divide)),
                    Operator.InfixL(Plus).And(Operator.InfixL(Minus)),
                    Operator.InfixL(EqualTo).And(Operator.InfixL(NotEqualTo))
                }
            ).Labelled("expression");

first time initialization takes 10s of seconds. As you can see we have only added a few operator conditions, is this to be expected?  Is there a better way to structure this?

2) We are interested in floating point support.  This was discussed in another thread ... any progress?

Thanks in advance.

Mark

**Comment by benjamin-hodgson** [comment]
Could you supply your full code please?

I agree that constructing parsers can sometimes be unacceptably slow at the moment. I have some plans to improve it, along with better error messages, in v2.0. In the meantime one tip I can offer is to use `Labelled` on your operator parsers and the components of `term`, I've seen that improve things.

**Comment by mustik22** [comment]
Thank you very much for the quick response.  

I have had a chance to go through the source a bit and I must say I am very impressed.  I like the way that you have structured the product and flow.  We are actually developing a much broader parsing feature set than the expression evaluation, and are seriously considering using your technology as a the base.

Here is the code as requested
(I am sure it will look familiar, as it was derived from a few of your examples)
[Archive.zip](https://github.com/benjamin-hodgson/Pidgin/files/2626384/Archive.zip)

By the way I had the same problems described in a few of the other threads getting the GIT Tree to fully compile. We are a C# Core 2.1 shop and I was able to get pieces to work, but not enough to help you diagnose the problem (other than it is definitely in the Build code).

I will try adding the Labelled property as you suggested.

Any thoughts on the availability of support for real (double) numeric data?

Kind regards.

**Comment by benjamin-hodgson** [comment]
Could you describe (perhaps in a separate issue) the problems you had building the sln? How exactly are you invoking msbuild?

**Comment by mustik22** [comment]
Potentially a big point is that we are a Mac shop and use Both Visual Studio and Visual Studio Code, with Azure. This forces us to run only Core 2.0/2.1 because of limitations on the publishing process. 

I will do the best I can to describe the process that I went through.  First I downloaded the tree and proceeded to attempt to build it (we do this for most of the 3rd party packages we run as a matter of course).  It opened fine in Visual Studio so I was hopeful.

First issue that I had was in the SDK base.  None of the projects appeared to work with Core 2.1 (I was surprised as I thought the older netstandard1.x versions should be compatible with the newer libraries).  I manually updated each of the project files so that that they were compatible. Went through a series of NuGet updates and and basically hacked at it until most of the projects compiled (Typical error is 'Resolving conflicts for .NETStandard,Version=v1.6...', 'Project Pidgin.Examples is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Project Pidgin.Examples supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)' etc.).  There are a number of dependencies between the projects which made the process a bit difficult. To date I have not been able to get the Pidgin.Bench.FParsec with FSharp to build (my guess is that FSharp.Core brings in the non core libraries and trying the pre-release of Microsoft.FSHarp.Core.netcore did not do the trick).

Even though the basic Pidgin library compiles (after resolving an unsafe ref issue), it does not run with our project. It gets through the expression build process, but fails with the following error when actually parsing an expression.

![image](https://user-images.githubusercontent.com/27729947/49185342-b9bd3f00-f32f-11e8-8c48-5c3274508b0e.png)

Which is ...
NullReferenceException: Object reference not set to an instance of an object.

Pidgin.TokenStreams.Unsafe.AsPointer<T>(ref ReadOnlySpan<T> span) in Unsafe.cs, line 11

This does not appear in the compiled 1.5 version from GIT.

Hope this was helpful.  Any tricks of the trade that would have made this process easier would be greatly appreciated.

Kind regards.

**Comment by benjamin-hodgson** [comment]
Partial fix for the performance issue: https://github.com/benjamin-hodgson/Pidgin/commit/30cb630124caeb8a5a687775e377b9a59f59fbac

**Comment by mustik22** [comment]
It looks like the changes in 30cb630 have had a significant impact on parser build. 

I was looking at at the project tree to potentially tackle the floating point feature and I had a quick question ... what is the purpose of the Pidgin.DllRewriter project?  

Thanks for making these changes and I look forward to their release.

**Comment by benjamin-hodgson** [comment]
0fc397afa62c021f6442cb2547e190547195720f

**Comment by benjamin-hodgson** [comment]
a0bda5c6ff492ba33cd4dd8084b2b489e2d53bd8

**Comment by benjamin-hodgson** [comment]
e3518ab26a0c64198cc64fbc334c11786547deaa

**Comment by benjamin-hodgson** [comment]
Shipped in v2.0.0
