### ISSUE TITLE
Does the DllRewriter break the PDB?

### ISSUE THREAD

**Issue by benjamin-hodgson** [benjamin-hodgson/Pidgin#19]

**Comment by benjamin-hodgson** [comment]
08936ec8b512cc40120d159f4f442ab8cdf2e4ff 998700b0f2a90519acf91d4890ae5642b2d7d0d1

**Comment by mustik22** [comment]
Confirmed, now able to debug Pidgin project.

Thanks

**Comment by andrewsav-datacom** [comment]
@benjamin-hodgson can you explain why is it safe to use the rewriting?

**Comment by andrewsav-datacom** [comment]
@benjamin-hodgson Is there a better way to contact you to clarify this?

**Comment by benjamin-hodgson** [comment]
@andrewsav-datacom This issue was just a bug in the build scripts. What would you like to know exactly?

**Comment by andrewsav-datacom** [comment]
@benjamin-hodgson apologies, my question was not related to the issue, now when you mentioned it, it was not very appropriate place to ask, I probably should have opened a new one.

The reason the compiler does not let you write this code and you have to do the rewriting, is because the compiler consider this unsafe. Of course the compiler does not know what you know, and is concerned with not letting you shoot yourself in the foot.

My question is: what about your use case that makes this rewriting safe?

Thank you in advance.

**Comment by benjamin-hodgson** [comment]
[The two methods in question](https://github.com/benjamin-hodgson/Pidgin/blob/master/Pidgin/TokenStreams/Unsafe.cs) aren't even expressible in `unsafe` C#, and in fact there's some almost identical code shipped as [an official .NET package](https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/). So I'd argue it's more an expressiveness issue than a safety one: you can't write it in C# because you _can't_, not because it's dangerous. It _is_ dangerous, but that's not why you can't write it. There are plenty of non-dangerous programs you can't write in C#, and there are plenty of dangerous programs you can write even in safe C#.

In this specific case the two methods convert a `ref Span<T>` to a `void*` and back. I need to do this so I can store a reference to a `Span` (living on the stack) [on the heap](https://github.com/benjamin-hodgson/Pidgin/blob/master/Pidgin/TokenStreams/SpanTokenStream.cs#L9). This is safe as long as the heap object containing the reference doesn't outlive the stack frame containing the span. I know this is true because I wrote my code carefully: [the `Parse` method](https://github.com/benjamin-hodgson/Pidgin/blob/master/Pidgin/ParserExtensions.cs#L108) is synchronous, and the `TokenStream` is not stored anywhere, so it'll become garbage before the `Span`'s stack frame is popped.

Sometimes you need to be allowed to point a gun at your foot in order to shoot a bug between your toes.

**Comment by benjamin-hodgson** [comment]
@andrewsav-datacom [The two methods in question](https://github.com/benjamin-hodgson/Pidgin/blob/master/Pidgin/TokenStreams/Unsafe.cs) aren't even expressible in `unsafe` C#, and in fact there's some almost identical code shipped as [an official .NET package](https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/). So I'd argue it's more an expressiveness issue than a safety one: you can't write it in C# because you _can't_, not because it's dangerous. It _is_ dangerous, but that's not why you can't write it. There are plenty of non-dangerous programs you can't write in C#, and there are plenty of dangerous programs you can write even in safe C#.

In this specific case the two methods convert a `ref Span<T>` to a `void*` and back. I need to do this so I can store a reference to a `Span` (living on the stack) [on the heap](https://github.com/benjamin-hodgson/Pidgin/blob/master/Pidgin/TokenStreams/SpanTokenStream.cs#L9). This is safe as long as the heap object containing the reference doesn't outlive the stack frame containing the span. I know this is true because I wrote my code carefully: [the `Parse` method](https://github.com/benjamin-hodgson/Pidgin/blob/master/Pidgin/ParserExtensions.cs#L108) is synchronous, and the `TokenStream` is not stored anywhere, so it'll become garbage before the `Span`'s stack frame is popped.

Sometimes you need to be allowed to point a gun at your foot in order to shoot a bug between your toes.
