### ISSUE TITLE
Parsing failure on multi-character sequences 

### ISSUE THREAD

**Issue by mustik22** [benjamin-hodgson/Pidgin#20]
Hi,

In the expression parser, an (partially) invalid string takes a long time to fail.  Ultimately the failure is reasonable, but the time it takes to fail may not be.  I am looking for advice on the structure of multi-character sequences, is there a better way?

Having lots of fun with this excellent tool!

Applicable Expression parsers
        private static readonly Parser<char, Func<IExpr, IExpr, IExpr>> EqualTo
           = Binary(Tok("=").Then(String("=")).ThenReturn(BinaryOperatorType.EqualTo));        // "=="

Input string
1=2

Expected 
1==2

Exception message
(reasonable)
Exception has occurred: CLR/Pidgin.ParseException
Exception thrown: 'Pidgin.ParseException' in Pidgin.dll: 'Parse error.
    unexpected 2
    expected expression
    at line 1, col 3'
   at Pidgin.ParserExtensions.GetValueOrThrow[TToken,T](Result`2 result)
   at Pidgin.ParserExtensions.ParseOrThrow[T](Parser`2 parser, String input, Func`3 calculatePos)
   at ApplicationSupport.Parsers.ExprParser.ParseOrThrow(String input) in /Users/mustik/Projects/ReservationCheck/ReservationCheck/Support/Parsers/ExprParser.cs:line 155

**Comment by benjamin-hodgson** [comment]
Please could you supply the code which reproduces the issue?

**Comment by mustik22** [comment]
My apologizes, I had not integrated with the latest version. Corrected and verified.

Source is in the pull request that I am preparing.
