### ISSUE TITLE
Name changement requested

### ISSUE THREAD

**Issue by Neustradamus** [benjamin-hodgson/Pidgin#24]
Can you change the name of this?

There is already Pidgin since a lot of years (formerly named Gaim):
- https://pidgin.im/

**Comment by benjamin-hodgson** [comment]
[I have spoken with](https://www.reddit.com/r/dotnet/comments/ak1jff/announcing_pidgin_v20/ef11ewd/) the maintainer of the chat app and he doesn't seem to mind.
