### ISSUE TITLE
XmlParser does not parse nested tags

### ISSUE THREAD

**Issue by cuongdn** [benjamin-hodgson/Pidgin#25]
Hello. 
I try running XmlParser in Pidgin.Examples and find out it does not parse nested tags. It only parse simple tag.
Can you please update the example or tell me how can fix it? Thanks

**Comment by benjamin-hodgson** [comment]
There's [a unit test](https://github.com/benjamin-hodgson/Pidgin/blob/master/Pidgin.Tests/XmlTest.cs#L54-L70) which checks that it does parse nested tags, so I suspect the problem is in your code. Please could you supply your code and your input?

**Comment by cuongdn** [comment]
I tried to change your input with some \r\n like below code and the result is fail. 
```[Fact]
public void TestParseTagWithContentAndAttributes()
{
        var input = @"<foo bar=""baz"" wibble=""wobble"">
                        <bar></bar>
                        <baz/>
                    </foo>";
        var expected = new Tag(
            "foo",
            new[] { new Attribute("bar", "baz"), new Attribute("wibble", "wobble") },
            new[] { new Tag("bar", new Attribute[]{}, new Tag[]{}), new Tag("baz", new Attribute[]{}, null) });
        
        var result = XmlParser.Parse(input);

        Assert.True(result.Success);
        Assert.NotNull(result.Value);
        Assert.Equal(expected, result.Value);
}
```

**Comment by benjamin-hodgson** [comment]
You just need to tweak the code in the example to consume whitespace. (The example is meant to be educational, not production-ready.)
