### ISSUE TITLE
Parsing all input?

### ISSUE THREAD

**Issue by wakuflair** [benjamin-hodgson/Pidgin#28]
This may be a stupid question, but I'm looking for something like `End()` in Sprache, but with no luck.

Like the code below:

``` chsarp
int num = Parser.Num.ParseOrThrow("1234aa");
```
Now it can parse `1234` successfully, but I need the parsing failed.

**Comment by benjamin-hodgson** [comment]
Yep it's called [`End`](https://www.benjamin.pizza/Pidgin/v2.0.1/api/Pidgin.Parser-1.html#Pidgin_Parser_1_End).

**Comment by wakuflair** [comment]
@benjamin-hodgson 
Yeah... I founded it. Thanks!
