### ISSUE TITLE
Parsing a non-delimited flat-file fixed-field-length string messages?

### ISSUE THREAD

**Issue by dinobu** [benjamin-hodgson/Pidgin#29]
What if I dont have delimiter but only flat-file style fixed-length string. Imagine getting data from a Tcp stream like this for example

`"\0\0\0j\0\0\0\vT3A1111 2999BOSH 2100021 399APV 2100022 "`

I cannot reliably rely on a delimiter here. The string above, represents a message received from a server with following meaning:

```
4  byte long message length      ("\0\0\0j") . THIS IS HEX value
4  byte long message id          ("\0\0\0\v"). THIS IS HEX value, the rest of values below are ASCII
1  byte long message type        ("T")
1  byte long message sequence    ("3")
8  byte long car Id              ("A1111   ")  
9  byte long part-1 price        ("     2999")
30 byte long part-1 manufacturer ("BOSH                          ")
9  byte long part#               ("2100021  ")
9  byte long part-2 price        ("      399")
30 byte long part-2 manufacturer ("APV                           ")
9  byte long part#               ("2100022  ")
```
How to parse message like this?

**Comment by benjamin-hodgson** [comment]
You don’t need a delimiter if you know how long the message is.

**Comment by dinobu** [comment]
> 
> 
> You don’t need a delimiter if you know how long the message is. Write a parser which consumes the correct number of bytes and then use `Many` to run it in a loop.

Would you mind elaborating a bit?  Thanks

**Comment by benjamin-hodgson** [comment]
Suppose for the sake of brevity that the message consists of only the first four fields:

```
4  byte long message length      ("\0\0\0j") . THIS IS HEX value
4  byte long message id          ("\0\0\0\v"). THIS IS HEX value, the rest of values below are ASCII
1  byte long message type        ("T")
1  byte long message sequence    ("3")
```

```csharp
Parser<byte, Message> message = Map(
    (length, id, type, sequence) => ...,
    Consume4Bytes,
    Consume4Bytes,
    Consume1Byte,
    Consume1Byte
);
```

`message` will always consume 10 bytes. To consume 10-byte chunks repeatedly, use `Many`.

```csharp
Parser<byte, IEnumerable<Message>> messages = message.Many();
```

No need to try to look for a non-existent delimiter.

**Comment by dinobu** [comment]
@benjamin-hodgson Cool, but the message does not exists of only 1st 10 bytes.  These 10 bytes will always be available but after that comes:

- 1 field representing CarId
- data that repeats representing PartPrice, PartManufacturer, PartId

So, I understand that there is no need for delimiter if fixed field length messaging is used but that is not my question.  **Sorry if I was not more clear but my question was more related to whether your library can be used to parse such message and how?**

Thanks,

**Comment by benjamin-hodgson** [comment]
You should've mentioned that the `Part` triple can occur multiple times. In your original question you said the message was a fixed length.

Anyway this is still quite easy to implement, you just need to repeat the parser which consumes a single part _n_ times, where _n_ is the number you read from the message header.

```csharp
Parser<Message> message =
    from numberOfParts in LengthField
    from header in Header
    from carId in CarId
    from partsList in Part.Repeat(numberOfParts)
    select new Message(header, carId, partsList);
```

Can probably be finessed a bit but the important part is `.Repeat(numberOfParts)`, where `numberOfParts` is dynamically determined from information earlier in the input.

**Comment by dinobu** [comment]
@benjamin-hodgson I said fixed-field-length, not fixed-length message.  The message example and the explanation also show that the fields #6, 7, 8 are repeating fields whereas fields #1, 2, 3, 4, 5 are not.
I stil dont understand how the LINQ parser example above can figure out that the fixed-length-field string has in this case 12 fields and what their lengths are.  In other words, I still dont understand, how this

```
Parser<Message> message =
    from numberOfParts in LengthField
    from header in Header
    from carId in CarId
    from partsList in Part.Repeat(numberOfParts)
    select new Message(header, carId, partsList);
```
can figure out that this string message:

<pre>"\0\0\0j\0\0\0\vT3A1111 2999BOSH 2100021 399APV 2100022 "</pre>

consists of 12 fields with this content

```
4  byte long message length      ("\0\0\0j") . This is HEX "j", so length is 106
4  byte long message id          ("\0\0\0\v"). This is HEX for "|", it is just a value of not importance for this question
1  byte long message type        ("T")
1  byte long message sequence    ("3")
8  byte long car Id              ("A1111   ")  
9  byte long part-1 price        ("     2999")
30 byte long part-1 manufacturer ("BOSH                          ")
9  byte long part#               ("2100021  ")
9  byte long part-2 price        ("      399")
30 byte long part-2 manufacturer ("APV                           ")
9  byte long part#               ("2100022  ")
```

**Comment by benjamin-hodgson** [comment]
You know how many repetitions of `Part` to expect based on the `length` field at the start of the message. In the code I gave you,

```csharp
    from n in LengthField
```

runs the `LengthField` parser (which would be a parser which consumes the first four bytes) and names the parser's result `n`.

Then, further down, the line

```csharp
    from parts in Part.Repeat(n)
```

runs the `Part` parser (which would be a parser which consumes the 48 bytes of the three repeating fields) `n` times.

You may need to tweak it a little - if the `length` is actually a length in bytes then it'll look something like `Part.Repeat((length - 18) / 48)`. But the important part is the number of times you run the `Part` parser depends on the value of the length field.
