### ISSUE TITLE
Add benchmark results to readme.md

### ISSUE THREAD

**Issue by Tyrrrz** [benjamin-hodgson/Pidgin#42]
Hey there,

Since Pidgin positions itself as the fastest parser combinator library, it would be really useful to see the output of https://github.com/benjamin-hodgson/Pidgin/tree/master/Pidgin.Bench in the readme.md for quick access.

**Comment by benjamin-hodgson** [comment]
Thanks for the suggestion! I'd be very happy to accept a pull request.

**Comment by Tyrrrz** [comment]
Done
