### ISSUE TITLE
Access Start/End SourcePos after successful parse

### ISSUE THREAD

**Issue by ronnieoverby** [benjamin-hodgson/Pidgin#43]
Is there a way to access the source begin/end positions?

I was hoping that ` Result<TToken, T>` would reveal something, but I don't see anything. If not, is this planned?

The use case is that I would be able to highlight parts of the parsed source while processing the resulting tree.

I suppose the ideal API would expose the starting/ending `SourcePos` from a successful result instance.

Apologies if you've addressed this question before; I didn't find any similar questions.

**Comment by benjamin-hodgson** [comment]
You can just grab the current source position at the beginning and the end of the parsing process.

```csharp
var p = Map(
    Tuple.Create,
    CurrentPos,
    wrappedParser,
    CurrentPos
);
```
