### ISSUE TITLE
Resumable Parsing

### ISSUE THREAD

**Issue by TehPers** [benjamin-hodgson/Pidgin#48]
I would love to be able to resume parsing once I finish parsing something. For example, it would be nice to do something like this:

```cs
IEnumerable<Token> ParseStream(TextReader stream) {
    var result = this.Parser.Parse(stream);
    while (result.Success) {
        yield return result.Value;
        result = result.ParseAgain(); // This would probably be implemented differently
    }
}
```

This would allow us to parse from an input stream as needed, without needing to store all the output tokens in memory. For example, we could process a 2GB+ file and write the output into another file without using very much memory.

Sprache has an equivalent to this, but does not support parsing from a stream:

```cs
IEnumerable<Token> ParseStream(string input) {
    var result = this.Parser.TryParse(input);
    while (result.WasSuccessful) {
        yield return result.Value;
        result = this.Parser(result.Remainder);
    }
}
```

One possible approach is to keep a reference to the `ParseState<T>` inside the object that `Parse` returns.

**Comment by benjamin-hodgson** [comment]
Does this work?

```csharp
IEnumerable<Token> ParseStream(TextReader stream)
{
    Result result;
    do
    {
        result = parser.Parse(stream);
        yield return result.Value;
    }
    while (result.Success);
}
```

After the call to `parser.Parse` the stream is left at the position the parser got up to.

**Comment by TehPers** [comment]
Yep, that works. Thank you!

**Comment by TehPers** [comment]
Sorry for reopening this. I'm still new to this library and I'm trying to use it for a class assignment.

This outputs 6:

```cs
private static void Main(string[] args)
{
    var parser = Parser.Digit;
    var input = "121528";

    using (var stream = new MemoryStream(Encoding.UTF8.GetBytes(input)))
    using (var reader = new StreamReader(stream))
    {
        parser.Parse(reader);
        Console.WriteLine(stream.Position);
    }
}
```

Shouldn't this output `1`? I think this is where my issue was coming up.

**Comment by benjamin-hodgson** [comment]
Ah, I think you're right. Because data is pulled from the stream in chunks, the parser reads ahead of where it potentially ends up. I guess the fix would be to rewind the stream (after checking `CanSeek`) after parsing, to where the parser actually consumed up to.

**Comment by benjamin-hodgson** [comment]
Would it be preferable to return the total count of tokens consumed (and possibly even the `SourcePos`?) as a property of the `Result`? Then you can rewind the stream yourself.

**Comment by TehPers** [comment]
I think returning an `IEnumerable<T>` that can be used to continue reading tokens would be helpful. It could maintain a buffer of tokens that have been read from the input source but not processed and return those first. For example:

```cs
IEnumerable<T> GetUnconsumedTokens() {
    foreach (var item in _buffer) {
        // You might want to remove the item at some point for memory purposes too, this is just an example
        yield return item;
    }

    // read from input here, this depends on the input type of course
}
```

This could be a method on `ITokenStream<T>` that is invoked and returned as part of the result maybe? I'm a little nervous about relying solely on the number of tokens consumed because knowing how many tokens were consumed doesn't mean that those tokens can be recovered. Input streams don't need to implement rewinding, and it's possible that re-enumerating an input `IEnumerable<T>` just to skip some number of tokens would be an expensive operation.

**Comment by benjamin-hodgson** [comment]
Ah yeah I quite like that idea. "Here are the tokens which I pulled from the input but didn't actually eat", ie, the remainder of the `ParseState`'s buffer.

**Comment by beho** [comment]
> Would it be preferable to return the total count of tokens consumed ~(and possibly even the `SourcePos`?)~ as a property of the `Result`? Then you can rewind the stream yourself.
> 
> Edit: On second thoughts you can already pull the `SourcePos` using `CurrentPos` so that's probably not necessary.

It might be more convenient to have `SourcePos` as part of the `Result`. Otherwise you have to append `CurrentPos` parser to every parser which sort of mixes multiple concerns together. Or is there any other way?

**Comment by TehPers** [comment]
I've been messing with this a bit and I agree that `SourcePos` should be part of the `Result`, although not for rewinding. It would be helpful to be able to pass that back into `Parse` later to tell the parser where the parsing began. For example, let's say you finish parsing at line 2, column 18. You probably want to tell the parser to continue parsing from there to make sure your `SourcePos` are accurate and you can get accurate error messages (if you rely on `SourcePos` for that).

Something that comes to mind is that the `SourcePos` could be tracked in `ParseState` and updated as parsing occurs. Bookmarks would probably need to also keep track of the `SourcePos` though. This is just an idea though, you could just call `ComputeSourcePos()` at the end but I think that relies on having all of the tokens you parsed stored in the buffer?

**Comment by benjamin-hodgson** [comment]
I've been kicking around the idea of replacing `SourcePos` with a similar but slightly different concept of a `SourcePosDelta`, representing the _change_ in source location since the beginning of parsing.

When you get to (eg) render an error message, you can concretise the `SourcePosDelta` by adding it to a specific `SourcePos`, which would be `(1, 1)` if you started parsing at the beginning of the file or `(1, 1) + previousDelta` if you'd already consumed `previousDelta`-worth of input.

Thoughts?

**Comment by benjamin-hodgson** [comment]
Code here: 4141044bc341e2c4be32f06fa93d56efdd65b25a

**Comment by benjamin-hodgson** [comment]
Regarding leftover tokens, I'm thinking it makes sense to make it part of the protocol between the parser and the `TokenStream`. I've added an `OnParserEnd(ReadOnlySpan<TToken>)` method to `ITokenStream`, to which the parser passes any unconsumed tokens. Code here (on the v3 branch): https://github.com/benjamin-hodgson/Pidgin/commit/015408c793ecd9b5bcf8efa9de3226552ea6cbdc
