### ISSUE TITLE
How to signal parsing failure from within Map?

### ISSUE THREAD

**Issue by mbcrawfo** [benjamin-hodgson/Pidgin#49]
Background: I need a parser that can consume an ISO-8601 into a `DateTime`.  I'm trying to avoid reinventing the wheel for all the valid of date and time format, so I'm leaning on `DateTime.Parse()`.  I need to parse out a string with Pidgin to send to `DateTime.Parse()`, but I don't actually know if that string is fully valid until I feed it through that parse method (code below).

Unfortunately there doesn't seem to be a way to indicate failure from within the "combine parser outputs" function that's passed to `Map`, so an invalid date string will causing parsing to fail with a `System.FormatException`.  Of course there's `TryParse()`, but once I know parsing has failed it doesn't seem like I can do anything with that info?

Is there a recommended way to handle this type of situation?

``` C#
internal static readonly Parser<char, IFilterExpression> DateTimeLiteral =
    SharedParsers.Token(
        Map(
            (year, rest) =>
            {
                var input = new string(year.ToArray()) + rest;
                var result = DateTime.Parse(
                    input,
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.RoundtripKind
                );

                return (IFilterExpression) new DateTimeLiteral(result);
            },
            Digit.Repeat(4),
            Char('-')
                .Then(
                    Try(Digit)
                        .Or(OneOf('-', ':', '.', 'T', 'Z'))
                        .ManyString(),
                    (head, tail) => head + tail
                )
        )
    );
```

**Comment by benjamin-hodgson** [comment]
Example [here](https://github.com/benjamin-hodgson/Pidgin/blob/9f087b55b0592aaf40e2452874cdd9e94e7765f3/Pidgin/Parser.Number.cs#L186). Or you could use `Then` and return `Fail`
