### ISSUE TITLE
[Question] Use of separator with sequenced parser

### ISSUE THREAD

**Issue by andr01d** [benjamin-hodgson/Pidgin#50]
Which is the way to apply the Separated method with a Sequenced parser because the following code returns the original string.

`private static readonly Parser<char, char> RBracket = Char(']');`
`private static readonly Parser<char, char> Asterisk = Char('*'); `
`static readonly Parser<char, Unit> EndDocument =`
      `RBracket.Then(Asterisk).Then(RBracket).ThenReturn(Unit.Value);`

`var test = Any`
               ` .ManyString()`
                `.Separated(EndDocument)`
                `.Parse("fd]*]vb]*]gf");`

**Comment by benjamin-hodgson** [comment]
`ManyString` is greedy, so `Any.ManyString()` will just consume the whole input (like `.*` in regex). You probably want something like `Letter.ManyString()`.
