### ISSUE TITLE
Parsing a list of unknown words

### ISSUE THREAD

**Issue by powerdude** [benjamin-hodgson/Pidgin#51]
Hi,

Sorry if this isn't the right place for questions, but how would you modify your XmlParser example so that it could parse `<foo>some text</foo>`.  Basically, adding an `InnerText` or `Text` property?

**Comment by benjamin-hodgson** [comment]
Add a subtype of `XmlNode` representing a text node, and write a parser for it which recognises text starting with a symbol other than `<`.
