### ISSUE TITLE
cast Parser<char>() to Parser<string>()?

### ISSUE THREAD

**Issue by Shadowblitz16** [benjamin-hodgson/Pidgin#60]
is it possible to cast a Parser< char >() to a Parser< string >()?
I can't post on stackoverflow because I will get downvoted and banned again.

**Comment by Shadowblitz16** [comment]
this is `Parser<char>.Once().Text()` I believe

**Comment by benjamin-hodgson** [comment]
`p.Map(c => c.ToString())`?
