### ISSUE TITLE
help with a ternary operator

### ISSUE THREAD

**Issue by iankho** [benjamin-hodgson/Pidgin#62]
Hi,

I would like to  parse a ternary expression with "comma " as operator for example:
CONTACT,RELATIONCODE->RELATION,SCALINGINDICATION,SEQNR = 'A'

the node structure should be like 
ARROW operator
     Left node
         Comma operator
             Left value: CONTACT
             Right value: RELATIONCODE
     Right Node
        DoubleComma operator
           Left value: RELATION
           Middle value: SCALINGINDICATION
           Right value:  SEQNR = "A" 

I manage to parse the binary operators but I am stuck with the ternary doublecomma operator.
Can some give me a push to the correct direction ?  

Regards Ian

**Comment by benjamin-hodgson** [comment]
What does your code look like so far?
