### ISSUE TITLE
Allow custom parser implementations

### ISSUE THREAD

**Issue by koliyo** [benjamin-hodgson/Pidgin#64]
I need to write a custom parser class but is unable to due to some classes/methods not having public access. Eg

```cs
        internal abstract InternalResult<T> Parse(ref ParseState<TToken> state);
```

Specifically what I want to do is create a parser that allows a result to be generated while also recording the position/range of the captured token.

**Comment by koliyo** [comment]
This is almost what the `MapWithInput` parser provides, but I would need both the span and the begin/end indices of the span.

And even if the `MapWithInput` parser provided what I needed, there could be other specialized parsers that could be implemented if those classes/methods were public.

**Comment by koliyo** [comment]
Here is a PR if you are interested, https://github.com/benjamin-hodgson/Pidgin/pull/65

**Comment by benjamin-hodgson** [comment]
Can you use [`CurrentPos`](https://www.benjamin.pizza/Pidgin/v2.2.0/api/Pidgin.Parser-1.html#Pidgin_Parser_1_CurrentPos) to get the position before and after the span?

I do have plans to publish an API for custom `Parser` subclasses, but it won't be in the form of just making all of the internals public. `ParseState` in particular is too much of a foot-gun to expose.

**Comment by koliyo** [comment]
Yes, the public API should probably be a bit more restrictive than just exposing all internal state.

Ah, didn't see the `CurrentPos` parser, I am pretty sure this can be used to implement the functionality I need.

**Comment by benjamin-hodgson** [comment]
This is implemented on the current main branch, which will be released as v3. I’m not 100% happy with the API as of yet though. There may be some more iteration before release, and the API should be considered unstable for a few versions.
