### ISSUE TITLE
Extend SourcePos struct with global stream token offset

### ISSUE THREAD

**Issue by koliyo** [benjamin-hodgson/Pidgin#66]
I would like to use not only the `(line, col)` info, but also the global offset in the input stream.

See earlier discussion in #65

**Comment by benjamin-hodgson** [comment]
I think this use case would be better served by a separate parser, something like:

```csharp
public static class Parser<TToken>
{
    public static Parser<TToken, int> CurrentOffset { get; }
}
```

**Comment by benjamin-hodgson** [comment]
Closed in https://github.com/benjamin-hodgson/Pidgin/commit/1744dec766af437845147d10049ebf109c8ca438
