### ISSUE TITLE
StackOverflowException in a specific scenario.

### ISSUE THREAD

**Issue by mykolav** [benjamin-hodgson/Pidgin#7]
Hi Benjamin,

If a debug build of Pidgin.dll is linked with a console app targeting .NET Framework 4.x, the app is  terminated due to StackOverflowException.

It looks like given the described configuration, CLR tries to eagerly initialize Parser.Optional._returnNothing and gets in an endless loop. Please take a look at the screenshot for an example.

![parser-optional-stack-overflow](https://user-images.githubusercontent.com/14280254/29213870-c71ddab2-7ead-11e7-870d-b2abf5b5e346.png)

Here is a minimal solution to reproduce the issue.
[ParserOptionalStackoverflow.zip](https://github.com/benjamin-hodgson/Pidgin/files/1217875/ParserOptionalStackoverflow.zip)

I took the liberty of including binary files (Pidgin.dll and friends) withing the archive.
If you prefer to remove them and rebuild yourself, here are the build commands.

```
dotnet restore
dotnet build --configuration Debug

```
Curiously enough:

- If a release build of Pidgin.dll is linked to the same console app, the bug does not reproduce.
- If a debug build of Pidgin.dll is linked to a .netcoreapp, the bug does not reproduce.

One way to correct this issue might be by preventing eager initialization in the following way

```
    public abstract partial class Parser<TToken, T>
    {
        private static Parser<TToken, Maybe<T>> _returnNothing;
        private static Parser<TToken, Maybe<T>> returnNothing => 
            _returnNothing ?? (_returnNothing = Parser<TToken>.Return(Maybe.Nothing<T>()));

        // Rest of the code left out for clarity
    }

```

The motivation to use a debug build of Pidgin is, while learning the library, it gives a way to figure out what is going on inside of Pidgin if something does not work as I expect it to.
By the way, thank you for a great talk -- https://www.youtube.com/watch?v=lsUgwfK9XIM

Thank you.
Mykola.

**Comment by benjamin-hodgson** [comment]
Excellent bug! Thanks for the report. I suspect there may be some subtleties to do with `beforefieldinit` in debug vs release mode. Suspect your fix is the way to go. I'll dig in.

**Comment by benjamin-hodgson** [comment]
Should be fixed with the latest master. Thanks for the bug report @mykolav!
