### ISSUE TITLE
operator overloads

### ISSUE THREAD

**Issue by furesoft** [benjamin-hodgson/Pidgin#70]
please add operator overload such as + and |

**Comment by benjamin-hodgson** [comment]
You can parse infix operators using [`ExpressionParser`](https://www.benjamin.pizza/Pidgin/v2.3.0/api/Pidgin.Expression.ExpressionParser.html).

**Comment by furesoft** [comment]
no i dont want to parse operators. i want to use operator overloads on a parser like:

parser1 + (parser2 | parser3)

**Comment by benjamin-hodgson** [comment]
How would you propose that to work?
