### ISSUE TITLE
ParseOrThrow does not throw expected exception

### ISSUE THREAD

**Issue by BambiShi** [benjamin-hodgson/Pidgin#72]
Hi,

I'm using the ParseOrThrow method and building my parser something like this:
Pidgin.Parser.OneOf(Chars)
Where Chars is Pidgin.Parser.Letter.Then(Pidgin.Parser.LetterOrDigit.ManyString(), (ch, str) => ch + str)
But when I have unexpected sign with the input the parser does not throw an exception: 
e.g: yu1*qwe
it will just behave as if there was only the "yu1"

Any idea how can I know there was an unexpected char in the input?

**Comment by jmlane** [comment]
`LetterOrDigit.ManyString()` only consumes 0 or more letters or digit characters without lookahead. In order to force an exception on the first unexpected character, you would need to use something like [Pidgin.Parser<TToken, T>.Until()](https://www.benjamin.pizza/Pidgin/v2.3.0/api/Pidgin.Parser-2.html#Pidgin_Parser_2_Until__1_Pidgin_Parser__0___0__) to continue consuming characters until the expected terminating character. E.g.:
```c#
using Pidgin;
using Pidgin.Parser;

try {
    Letter
        .Then(LetterOrDigit.Until(EndOfLine), (ch, str) +> ch + str)
        .ParseOrThrow(input);
}
catch (ParseException exception) {
    // ...
}
```

**Comment by BambiShi** [comment]
Hi, 
Thanks for your response!

The code is a little more complicated.
I'm using operators between the 
Pidgin.Parser.Letter.Then(Pidgin.Parser.LetterOrDigit.ManyString(), (ch, str) => ch + str)
so it reads until it finds the operator, but if instead of operator there is an unexpected character it just won't fail:

example: my input: Q5+W6-E7 => where the "-" and "+" are the operators, so it needs to parse separately the Q5 and W6 and E7.
but if instead of + or - I'll have for example *: Q5*W6 => the "*" is an unexpected character, but it won't throw an exception, it will only parse the Q5 and stop from there

**Comment by jmlane** [comment]
How is your outer "expression" parser structured—the parser that consumes your operand parser and handles the operators? If `*` is not a valid separating character, the outer parser can throw an exception if it is encountered before the expected end of input.

**Comment by benjamin-hodgson** [comment]
Try throwing `.Before(End)` onto your outermost parser.

**Comment by BambiShi** [comment]
What does the "End" mean?
I want to have .Before(EndOfFile).
Is there a way to do that?

**Comment by benjamin-hodgson** [comment]
Yes, that’s what End does.
