### ISSUE TITLE
Documentation link leads to a 404

### ISSUE THREAD

**Issue by john-cullen** [benjamin-hodgson/Pidgin#73]
https://www.benjamin.pizza/Pidgin does not seem to be working at the moment

**Comment by benjamin-hodgson** [comment]
Thanks for the report, looks like there's an ongoing issue with the GH Pages deployment. I'll look into it. In the mean time the previous version's docs are still available: https://www.benjamin.pizza/Pidgin/v2.3.0/api/Pidgin.html

**Comment by benjamin-hodgson** [comment]
Looks like we're back up! Thanks again for the bug report
