### ISSUE TITLE
Case insensitive parsing & raising errors from inside Select / Map

### ISSUE THREAD

**Issue by john-cullen** [benjamin-hodgson/Pidgin#74]
Hello,

Is there an option for case insenstive parsing available? For example I'm using Pidgin to parse a command line interface and for user-friendliness we generally ignore case in our system.

Also, is it possible to do something inside a Select or Map which will cause the parser to return a failure? If I throw a regular exception it does not get caught in the parser.

Cheers

**Comment by jmlane** [comment]
For case insensitive parsing, you can use [CIChar](https://www.benjamin.pizza/Pidgin/v2.3.0/api/Pidgin.Parser.html#Pidgin_Parser_CIChar_System_Char_) and [CIString](https://www.benjamin.pizza/Pidgin/v2.3.0/api/Pidgin.Parser.html#Pidgin_Parser_CIString_System_String_).

**Comment by benjamin-hodgson** [comment]
To abort at a given point in the parse script you need to invoke the `Fail` parser, which means replacing `Select` with a combination of `Then` and `Return`. So

```
myParser.Select(x => ShouldFail(x) ? throw new Exception() : Foo(x))
```
becomes
```
myParser.Then(x => ShouldFail(x) ? Fail<FooResult>() : Foo(x))
```

**Comment by john-cullen** [comment]
Thanks, I didn't see the CIString / CIChar types.

I successfully used the `.Then` example but my `Fail` message isn't getting returned in the result object. I assume that what's happening is that once that `Fail` parser gets hit it triggers the backtracking since the parser is wrapped in `Try` and then whatever the last parser in the `OneOf` gets its failure message returned instead.

Maybe I can refactor my parsers to fix that but in case I can't is there any way around this?

**Comment by benjamin-hodgson** [comment]
`OneOf` returns the error from the longest match. Could you give a concrete example of a case where that's not desirable?

**Comment by john-cullen** [comment]
My parser is for an in-app command language like `set setting example index=2`. The 'options' (prefined tokens, `set` and `setting` in the above example) may be arbitrarily deep, and 'parameters' (user-supplied values, 'example' and 'index=2') my be supplied either positionally or by name, and may be optional. The only rules are that options (options are always positional) must appear before parameters, and optional parameters must appear after positional parameters. Parameters may be text, numbers, or booleans. 

I'm using a `.Select` to verify that keys are known and that parameter values are in the correct form. 

It sounds like I may need to move some of these checks to a separate step that runs after the parser has returned a result though?

**Comment by benjamin-hodgson** [comment]
I may not have understood you 100%, but here's roughly how I'd write your parser:

```csharp
Parser<char, string> Keyword(string keyword)
    => Try(keyword.Before(Whitespace.Or(End))).Before(SkipWhitespaces);

Parser<char, string> Option = OneOf(new[] { "set", "setting", "etc" }.Select(Keyword));
Parser<char, (string, Maybe<int>)> Param =
    from name in Letter.ManyString
    from value in Char('=').Then(Num).Optional()
    from _ in SkipWhitespaces
    select (name, value);

Parser<char, Cmd> Command =
    from options in Option.AtLeastOnce()
    from params in Param.Many()
    select new Cmd(options, params);
```

I haven't tested this code but the `Option` parser _should_ correctly report something like `expected "set", "setting", "etc"` when you feed it an unknown option. (I mean to say that it's supposed to do that but it might have a bug!)

**Comment by john-cullen** [comment]
I think the problem is that it's actually 

'show -> setting | script | job | example'

so `set setting example autostart true` is valid (and could also be written `set setting value=true key=autostart`), and so is `show job 12`, what I'm trying to do is make useful error messages get returned if you do `show job !"£$$%` for example. What I end up getting is `expected one of "script", "example"`.

**Comment by benjamin-hodgson** [comment]
It sounds like your check is more of a semantic analysis than a syntactic one, that is, better implemented as a post-parsing pass

**Comment by john-cullen** [comment]
Alright, thanks a lot for your help! Great little library you have here.

**Comment by benjamin-hodgson** [comment]
Thanks for your interest! ❤️
