### ISSUE TITLE
Pidgin.dll is not signed

### ISSUE THREAD

**Issue by BambiShi** [benjamin-hodgson/Pidgin#76]
Hi,

I want to use Pidgin.dll from nuget but the dll is not signed. (PublicKey=null)
I can't use dll that are not strongly named.

Is there a version in nuget that the dll is signed?
Is there a plan to release a version that is signed?

Thanks a lot!

**Comment by benjamin-hodgson** [comment]
Fixed in 0e48afe

**Comment by BambiShi** [comment]
Thanks a lot!

Any idea when it will be released as an official release?

‫בתאריך יום ג׳, 23 ביוני 2020 ב-18:58 מאת ‪Benjamin Hodgson‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by benjamin-hodgson** [comment]
It should be up now (2.5.0)
