### ISSUE TITLE
Pidgin.dll Using System.Runtime.CompileServices

### ISSUE THREAD

**Issue by BambiShi** [benjamin-hodgson/Pidgin#77]
Hi,

I've notice that the last version of Pidgin (2.4.0) is using the System.Runtime.CompileServices.

It seems like there is no reference to that, but it is part of Pidgin.
Here: https://www.benjamin.pizza/Pidgin/v2.3.0/api/Pidgin.html it doesn't seem like it is using that.

Is that reference really needed?
I'm having some issues with it so was wondering if it is necessary at all.

Is there a version a Pidgin without the System.Runtime.CompileServices.

Thanks in advance!

**Comment by benjamin-hodgson** [comment]
Sorry, I don't understand the question. The CompilerServices namespace is part of .NET. A variety of the APIs in that namespace are used internally by the lib.

**Comment by BambiShi** [comment]
I looked at the references of the Pidgin.dll and there is not reference to the CompilerServices. It apears as part of the Pidgin itself - and that is what's weird and causes issues:

![image](https://user-images.githubusercontent.com/29270394/85382524-bad44380-b547-11ea-9ac3-0d0e54a7e240.png)

As can be seen here, it doesn't appear in the list of references but appears as part of the project itself

**Comment by benjamin-hodgson** [comment]
If you open it up you should see that it's just the nullable attributes which are emitted by the compiler
