### ISSUE TITLE
I get error Many() used with a parser which consumed no input

### ISSUE THREAD

**Issue by iozcelik** [benjamin-hodgson/Pidgin#84]
I try to parse statement until the string and after the string.

```
var input = "prefix{{test='5'}}middle{{'test string'}}postfix";
```

I try to get result List<ITest> and it prepare 5 items correctly. However last time an "" char goes parser and throw "Many() used with a parser which consumed no input" exception.

My expected result set:
1. `Text `item with name prefix
2. `Test2 `item with name test string
3. `Text `item with name middle
4. `Test1 `item with name test
5. `Text `item with name postfix

Also, I use `LetterOrDigit` in prefix, postfix or middle but it may any char like dot or comma.

```csharp
    public class TestParser {
        private static readonly Parser<char, string> ObjectStart = String("{{");
        private static readonly Parser<char, string> ObjectEnd = String("}}");
        private static readonly Parser<char, string> Equal = String("=");

        private static Parser<char, T> Tok<T>(Parser<char, T> token) => Try(token).Before(SkipWhitespaces);
        private static Parser<char, string> Tok(string token) => Tok(String(token));

        private static readonly Parser<char, string> StringLiteralDouble = Tok(Try(String("\"\"")).ThenReturn('"')
                .Or(Token(c => c != '"'))
                .ManyString()
                .Between(Char('"')));

        private static readonly Parser<char, string> StringLiteralSingle = Tok(Try(String("''")).ThenReturn('\'')
                .Or(Token(c => c != '\''))
                .ManyString()
                .Between(Char('\'')));

        private static readonly Parser<char, string> StringLiteral = Tok(OneOf(StringLiteralDouble, StringLiteralSingle));

        private static readonly Parser<char, ITest> PrefixStatement = LetterOrDigit.ManyString().Before(String(string.Empty)).Select<ITest>(s => new Text(s));
        private static readonly Parser<char, ITest> MiddleStatement = LetterOrDigit.ManyString().Between(String(string.Empty), String(string.Empty)).Select<ITest>(s => new Text(s));
        private static readonly Parser<char, ITest> PostfixStatement = LetterOrDigit.ManyString().Select<ITest>(s => new Text(s));


        private static readonly Parser<char, ITest> Test1Statement = Tok(StringLiteral.Between(Whitespaces).Between(ObjectStart, ObjectEnd))
            .Select<ITest>(s => new Test1(s));
        private static readonly Parser<char, ITest> Test2Statement = Tok(Letter.ManyString()).Before(Tok(Equal))
            .Then(OneOf(Num.Select<dynamic>(s => s), Real.Select<dynamic>(s => s), StringLiteral.Select<dynamic>(s => s), LetterOrDigit.ManyString().Select<dynamic>(s => s)), (s, v) => new Test2(s, v)).Between(ObjectStart, ObjectEnd)
            .Select<ITest>(s => s);


        private static readonly Parser<char, ITest> Statement = OneOf(Test1Statement, Test2Statement, PrefixStatement, MiddleStatement, PostfixStatement);
        private static readonly Parser<char, IEnumerable<ITest>> Statements = Statement.Many();

        public static Result<char, IEnumerable<ITest>> Parse(string input) => Statements.Parse(input);
    }

    public interface ITest {
        string Name { get; }
    }

    public class Test1 : ITest {
        public string Name { get; }
        public Test1(string name) {
            Name = name;
        }
    }

    public class Test2 : ITest {
        public string Name { get; }
        public dynamic Value { get; }
        public Test2(string name, dynamic value) {
            Name = name;
            Value = value;
        }
    }

    public class Text : ITest {
        public string Name { get; }
        public Text(string name) {
            Name = name;
        }
    }
```

**Comment by benjamin-hodgson** [comment]
Looks like (eg) `PrefixStatement` can succeed without consuming input.

**Comment by iozcelik** [comment]
Ok, but how can I get the result? Because string.Empty is not best solution and I get always string.Empty at last.

**Comment by iozcelik** [comment]
@benjamin-hodgson what do you mean consuming input. Because in debug all text objects created. Last statment get an error. I think this not be close.

**Comment by benjamin-hodgson** [comment]
If you call `Many` on a parser which can succeed without consuming any text from the input file then it will loop for ever. `OneOf(Test1Statement, Test2Statement, PrefixStatement, MiddleStatement, PostfixStatement)` can succeed without consuming input because `PrefixStatement` can.

**Comment by iozcelik** [comment]
@benjamin-hodgson I understand previous answer and this looking same. My aim get the expected result. Obviously, I am doing something wrong.

I need `Many()` after statement because I wait multiple statement. However what is the correct way of this parser? Using `string.empty` is totally wrong. However what can I use? `Until()` does not stop consuming match a string or char. By the way I dont want to use `LetterOrDigit.ManyString()` because in here may be input contains dot or comma.

**Comment by benjamin-hodgson** [comment]
You need to make sure each of your component parsers won't succeed without consuming any input.

**Comment by iozcelik** [comment]
@benjamin-hodgson How? 

> My expected result set:

> Text item with name prefix
> Test2 item with name test string
> Text item with name middle
> Test1 item with name test
> Text item with name postfix

I got this result from shared code. But I got an unexpected "" string. It cause error. I debug Pidgin code to get this.

**Comment by benjamin-hodgson** [comment]
Yes, because your `PrefixParser` succeeded without consuming input.

**Comment by iozcelik** [comment]
Yes, how I stop this? I cant successed.

**Comment by benjamin-hodgson** [comment]
You need to modify `PrefixStatement` so that it always either fails or consumes at least one character. I don't know exactly what you're trying to do, but something like

<pre><code>PrefixStatement = LetterOrDigit.<b>AtLeastOnceString</b>().Select<ITest>(s => new Text(s));</code></pre>

should solve the immediate issue

**Comment by iozcelik** [comment]
I write my aim first comment. I have an input string and I try get a list of items. {{ and }} using for special purpose. But I also need before and after strings. 

Ignore my code, what's your advice? Could you share an example?

**Comment by iozcelik** [comment]
This working correctly.

```csharp
private static readonly Parser<char, ITest> Test1Statement = Tok(StringLiteral.Between(Whitespaces).Between(ObjectStart, ObjectEnd))
            .Select<ITest>(s => new Test1(s));
        private static readonly Parser<char, ITest> Test2Statement = Tok(Letter.ManyString()).Before(Tok(Equal))
            .Then(OneOf(Num.Select<dynamic>(s => s), Real.Select<dynamic>(s => s), StringLiteral.Select<dynamic>(s => s), LetterOrDigit.ManyString().Select<dynamic>(s => s)), (s, v) => new Test2(s, v)).Between(ObjectStart, ObjectEnd)
            .Select<ITest>(s => s);

        private static readonly Parser<char, ITest> TextStatement = LetterOrDigit.AtLeastOnceString().Select<ITest>(s => new Text(s));


        private static readonly Parser<char, ITest> Statement = OneOf(Test1Statement, Test2Statement, TextStatement);
        private static readonly Parser<char, IEnumerable<ITest>> Statements = Statement.Many();

        public static Result<char, IEnumerable<ITest>> Parse(string input) => Statements.Parse(input);
```
