### ISSUE TITLE
[Suggestion] AnyStringExcept method like AnyCharExcept('f','g').AtLeastOnceString()

### ISSUE THREAD

**Issue by iozcelik** [benjamin-hodgson/Pidgin#87]
In `AnyCharExcept('f','g').AtLeastOnceString()` method consume until meet a char inside list.

```
abcdefghijklmno
     ^
```

Consumed input: abcde

When using together `AtLeastOnceString`, it make very easy parsing. However, if I want to except strings? It is not easy like that.

For example below code return a string array with **4 items**. It is perfect. When I am working strings, I wish a method `AnyStringExcept`... Of course, they may different ways to do it, but I do not find an easy way.

This method like a combine of `AnyCharExcept` and `AtLeastOnceString` has 3 overloads.
```csharp
public static Parser<char, string> AnyStringExcept(params string[] strings)
public static Parser<char, string> AnyStringExcept(IEnumerable<string> strings)
public static Parser<char, string> AnyStringExcept(Parser<char, string> parsers)
```

Behavior: When match any string in parameter list, stop consume and continue next operation.
```
AnyStringExcept("fg")

abcdefghijklmno
     ^^
```
Consumed input: abcde
If we work below code with this method, get a string array with **3 items**.

```csharp
class Program {
        static void Main(string[] args) {
            var input = "abcdefghijklmno";

            var result = DemoParser.Parse(input);
            var text = result.Value;
            foreach (var item in text) {
                Console.WriteLine(item);
            }
            Console.ReadLine();
        }
    }

    public class DemoParser {
        private static readonly Parser<char, string> FChar = String("f");
        private static readonly Parser<char, string> GChar = String("g");

        private static readonly Parser<char, string> OtherString = AnyCharExcept('f', 'g').AtLeastOnceString().Select(s => s);
        //private static readonly Parser<char, string> OtherString = AnyStringExcept("fg").Select(s => s);

        private static readonly Parser<char, string> MyString = OneOf(FChar, GChar, OtherString);
        private static readonly Parser<char, IEnumerable<string>> MyStrings = MyString.Many();

        public static Result<char, IEnumerable<string>> Parse(string input) => MyStrings.Parse(input);
    }
```

**Comment by benjamin-hodgson** [comment]
Isn't this just `Any.Until(Lookahead(String("fg")))`?

**Comment by iozcelik** [comment]
Ok, I try to make it clear. Are `AnyCharExcept('f','g').AtLeastOnceString()` and `Any.Until(Lookahead(Char('f').Or(Char('g')))).Select(s => new string(s.ToArray()))` equal? They are not.

Because Lookahead, make it own job and look ahead.

If we work above code with below line:
`private static readonly Parser<char, string> OtherString = AnyCharExcept('f', 'g').AtLeastOnceString().Select(s => s);`
we get that result:
`string[]{"abcde","f","g","hijklmno"}`

However if use Lookahead
`private static readonly Parser<char, string> OtherString = Any.Until(Lookahead(Char('f').Or(Char('g')))).Select(s => new string(s.ToArray()));`
we get an exception message.
`Can't get the value of an unsuccessful result`

This is expected because of there is no more 'f' or 'g' char end of the string.

The idea is same. If we use `AnyStringExcept("fg")`, we should get `string[]{"abcde","f","g","hijklmno"}` this result. However if we use `Any.Until(Lookahead(String("fg")))`, we get the same exception `Can't get the value of an unsuccessful result`. 

So `AnyStringExcept("fg")` and `Any.Until(Lookahead(String("fg")))` are not same. May be they are looking similar first match but if string does not contains "fg" at last, they act totaly different.

`Lookahead` working:
```
abcdefghijklmno
     ^^           -> First match of Any.Until(Lookahead(String("fg")))
     ^            -> Match of String("f")
      ^           -> Match of String("g")
               ^^ -> Lookahead for "fg" again but there is no more!! So throw exception.
```

`AnyStringExcept` working:
```
abcdefghijklmno
     ^^           -> First index of "fg" and consume until here
     ^            -> Match of String("f")
      ^           -> Match of String("g")
                  -> There is no more "fg" so consume and of string
```

**Comment by benjamin-hodgson** [comment]
I think you're experiencing the [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem). You just need to tweak how your `Until` parser handles the end of the input. `Any.Until(Lookahead(String("fg")).Or(End))` does exactly what you want.

**Comment by iozcelik** [comment]
If you read first post I said it is possible. So you can remove AnyCharExcept, because it is possible by another way. Also or, oneof...

Why they multiple? Anyway I just suggest easy and simple method. You know...

**Comment by iozcelik** [comment]
Your advice is not working.
![image](https://user-images.githubusercontent.com/10682780/101198741-fb96c380-3674-11eb-8726-4ebcdb574c85.png)
