### ISSUE TITLE
Any.Until(Lookahead(String("fg")).Or(End)) is not working expected

### ISSUE THREAD

**Issue by iozcelik** [benjamin-hodgson/Pidgin#88]
[In that comment](https://github.com/benjamin-hodgson/Pidgin/issues/87#issuecomment-738873444) `Any.Until(Lookahead(String("fg")).Or(End))` adviced me. However it is not working.
![image](https://user-images.githubusercontent.com/10682780/101198741-fb96c380-3674-11eb-8726-4ebcdb574c85.png)

I try to solve my problem in [here](https://stackoverflow.com/questions/65102725/pidgin-consume-any-char-until-match-and-not-consume-second-match?noredirect=1#comment115096049_65102725) and I lost my days. 
- Anybody doesn't help including author.
- Answers aren't helpful.
- This library may be fast but community is not friendly. 
- I don't have to know details. I am only user, if author cannot help me, it is OK. However, in an open source project, you shouldn't close an issue until solving problem.

**Comment by benjamin-hodgson** [comment]
It's a type mismatch. `Lookahead(String("fg"))` is a parser which returns a string; `End` is a parser which returns nothing. `p.Or(q)` needs the types of `p` and `q` to match.

The fix in this case is to [ignore the result](https://www.benjamin.pizza/Pidgin/v2.5.0/api/Pidgin.Parser-2.html#Pidgin_Parser_2_IgnoreResult) of the `String` parser:

```csharp
Any.Until(Lookahead(String("fg")).IgnoreResult().Or(End))
```

**Comment by iozcelik** [comment]
If I do it, again come \0. And it cause [again](https://github.com/benjamin-hodgson/Pidgin/issues/84) `System.InvalidOperationException: 'Many() used with a parser which consumed no input'` You mentioned `.AtLeastOnceString()` in that issue. And I try to it in here but nothing happened.

![image](https://user-images.githubusercontent.com/10682780/101209281-8c28d000-3684-11eb-8c8c-7360b794d8f5.png)

**Comment by benjamin-hodgson** [comment]
Try `AtLeastOnceUntil` in place of `Until`?

**Comment by iozcelik** [comment]
I cannot solve [my problem](https://stackoverflow.com/questions/65102725/pidgin-consume-any-char-until-match-and-not-consume-second-match) completely but this question answered. Thanks!! `AtLeastOnceUntil` works but `Any.AtLeastOnceUntil(OneOf(Try(Lookahead(String("cf"))).IgnoreResult(),Try(Lookahead(String("cd"))).IgnoreResult(),  End))` is too long for this operation. I renew my suggestion, it will be simple. `AnyStringExcept("cf","cd")`
