### ISSUE TITLE
Getting 'Unexpected EOF' when using any and between

### ISSUE THREAD

**Issue by iozcelik** [benjamin-hodgson/Pidgin#89]
Any matches any character and AtLeastOnceString is packt into a string. But I got this every time.

What I try?
`Any.AtLeastOnceString().Until(End).Between(String("{{"),String("}}"));`
`Any.Until(End).Between(String("{{"),String("}}"));`
`LetterOrDigit.Or(Punctuation).Between(String("{{"),String("}}"));`

![image](https://user-images.githubusercontent.com/10682780/101222864-c2be1500-369b-11eb-8258-4639b8ce6e92.png)

**Comment by benjamin-hodgson** [comment]
`Any` matches **any character**. `Any.AtLeastOnceString()` will always greedily consume input until the end, including the closing `}}` in your example. By the time `String("}}")` gets invoked the braces will have already been consumed.

You need to change the loop to consume input except for your `}}` delimiter. That's what the `Until(Lookahead(String("}}")))` was for.

```csharp
parser = Any
    .AtLeastOnceUntil(Lookahead(String("}}")))
    .Select(chars => new string(chars.ToArray()))
    .Between(String("{{"), String("}}"));
```

**Comment by iozcelik** [comment]
Thanks for clear explain. Now, I really solve lots of my problems.
