### ISSUE TITLE
[Question] Is it possible to multiple nested object with recursive

### ISSUE THREAD

**Issue by iozcelik** [benjamin-hodgson/Pidgin#90]
In expression parser example, I get the point and making some tests with it. All successed. But in here, I do not have actually an binary or any operation. 

I collect data from a device and it sends like data like `"(test1(test2)test3)"`, `"(test1(test2(test3)))"`...
```
Parser<char, string> expr = null;
var parenthesised = String("(").Then(Rec(() => expr)).Before(String(")"));
expr = parenthesised.Or(LetterOrDigit.AtLeastOnceString());
var result = expr.Parse("(test1(test2)test3)");
```
I try to get `"test1", "test2" and "test3"`

How to made it?

**Comment by benjamin-hodgson** [comment]
You have a parser to read a single string in arbitrarily-nested parentheses, so you just need to adjust it to read a number of such strings.

```csharp
Parser<char, IEnumerable<string>> expr = null;
var parenthesised = Rec(() => expr).Between(Char('('), Char(')'));
expr = parenthesised
    .Or(LetterOrDigit.AtLeastOnceString().Select(x => new[] { x }))
    .Many()
    .Select(xss => xss.SelectMany(xs => xs));  // flatten nested list
```

There is some room for finessing here, such as whether you want to allow inputs such as `(foo)(bar)`, but I'll leave that up to you.

**Comment by iozcelik** [comment]
In here type not matched;

I change some codes and consume some inputs but it is not completed.

![image](https://user-images.githubusercontent.com/10682780/101394301-5a5c7700-38d9-11eb-92f4-12e71759a6d8.png)

Is using expression parser better in here? I have no binary or arithmetic operation. So that, I can't give any parameter to expression parser.

**Comment by benjamin-hodgson** [comment]
You just need to cast it to IEnumerable
