### ISSUE TITLE
Prolog Parser Example Doesn't Compile

### ISSUE THREAD

**Issue by SenorAgosto** [benjamin-hodgson/Pidgin#94]
I'm trying to implement the Prolog Parser example from [your blog post](https://www.benjamin.pizza/posts/2019-12-08-parsing-prolog-with-pidgin.html). 

I'm getting an error on the line:

    static Parser<char, T> Tok<T>(Parser<char, T> p) => Try(p).Then(SkipWhitespaces);
    
Error: 

    CS0029: Cannot implicitly convert type 'Pidgin.Parser<char, Pidgin.Unit>' to 'Pidgin.Parser<char,T>'

Interestingly, if I change `.Then(SkipWhitespaces)` to `.Before(SkipWhitespaces)` the compiler is happy. Sorry, I'm probably missing something obvious, I'm not much of a C# guy.

In a .NET Standard 2.0 library, with Pidgin 2.5.0.

**Comment by SenorAgosto** [comment]
This might not actually be an issue with Pidgin, but with the blog post. Looking at the blog's [example code](https://github.com/benjamin-hodgson/Amateurlog/blob/master/Parser.cs) in git, it uses `.Before(SkipWhitespaces)` not `.Then(SkipWhitespaces)`.

**Comment by benjamin-hodgson** [comment]
You’re quite right, this was a typo in the post. It should say `Before`. Thanks!
