### ISSUE TITLE
How to restrict type of expression

### ISSUE THREAD

**Issue by jccockre** [benjamin-hodgson/Pidgin#95]
Hello,

Would it be possible to get an example of an expression parser which restricts the part outside the parentheses to be an identifier, not just any expression?

I wrote the following simple test:

        [Test]
        public void TestCall01()
        {
            Assert.NotNull(ExprParser.ParseOrThrow("Power(2, 10)"));
            Assert.Throws<Exception>(() => ExprParser.ParseOrThrow("8(2, 10)"));
        }

From what I can tell, it seems the expression parser provided with the examples considers 8(2, 10) to be a method call with 8 as the method name. I tried to figure out how to impose a restriction that the method name must be an identifier, but I keep getting compiler errors. It feels like I can't mix-and-match parsing expressions with identifiers.

**Comment by jccockre** [comment]
Re-reading the above, I don't think I did a good job of articulating what I'm trying to accomplish. But I was able to make progress toward a solution anyway. I defined the following classes:

    public class ArgumentsWrapper : IExpr
    {
        public ImmutableArray<IExpr> Arguments { get; }
        public ArgumentsWrapper (ImmutableArray<IExpr> arguments)
        {
            Arguments = arguments;
        }
        public bool Equals(IExpr other)
            => other is ArgumentsWrapper a
            && this.Arguments.SequenceEqual(a.Arguments);
    }
    public class MyCall : IExpr
    {
        public IExpr Expr { get; }
        public IExpr Arguments { get; }

        public MyCall(IExpr expr, IExpr arguments)
        {
            Expr = expr;
            Arguments = arguments;
        }

        public bool Equals(IExpr other)
            => other is MyCall c
            && this.Expr.Equals(c.Expr)
            && this.Arguments.Equals(c.Arguments);
    }

`MyCall` replaces `Call` from the example files, then I defined the parser:

        private static Parser<char, IExpr> MyCall(Parser<char, IExpr> subExpr)
            => Identifier.Then<IExpr, IExpr>(Parenthesised(subExpr.Separated(Tok(",")))
                .Select<IExpr>(args => new ArgumentsWrapper(args.ToImmutableArray())),
                (method, wrapper) => new MyCall(method, wrapper));

Lastly I changed the way this is used in the `Expr` parser:

        public static readonly Parser<char, IExpr> Expr = ExpressionParser.Build<char, IExpr>(
            expr => (
                OneOf<char, IExpr>(
                    Try(MyCall(expr)),   // -- ADDED THIS
                    Parenthesised(expr).Labelled("parenthesised expression"),
                    Literal,
                    Identifier
                ),
                new OperatorTableRow<char, IExpr>[]
                {
                    //Operator.PostfixChainable(Call(expr)),  -- REMOVED THIS
                    Operator.Prefix(Neg).And(Operator.Prefix(Complement)),
                    Operator.InfixR<char, IExpr>(Dereference),
                    Operator.InfixL(Mul),
                    Operator.InfixL(Div),
                    Operator.InfixL(Add),
                    Operator.InfixL(Sub)
                }
            )
        ).Labelled("expression");

The important consequence of this is that something like `8(2, 10)` won't be parsed as a method call, because `8` is not an `Identifier`. 

I'm going to close this now since I got where I wanted to go, but if you think these changes would be a useful contribution to the examples, I can clean up the code and submit.

**Comment by benjamin-hodgson** [comment]
Thanks for your interest! Sorry for the delay in responding. The parser in your second post looks basically correct - changing the call parser from being an operator to part of the term parser is the way to go. It does look like you have a little type-unsafety in there, though.

In [the example code](https://github.com/benjamin-hodgson/Pidgin/blob/0ef39a9aa4dfff067115ef7d3c9fd77b5c5c009e/Pidgin.Examples/Expression/ExprParser.cs#L57), the "call" operator is treated as a postfix operator. This means the "callable thing" to the left of the parentheses can be any expression.

It sounds like in your syntax, the thing on the left of the parentheses is meant to be an identifier, not an arbitrary expression. This suggests that the way you've modelled it in your datatype is a bit misleading:

```csharp
public class Call : IExpr
{
    public IExpr Expr { get; }  // can be any expression, not specifically an identifier
    public IExpr Arguments { get; }  // can be any expression, not specifically a sequence of arguments
}
```

Instead I'd design your `Call` like this:

```csharp
public class Call : IExpr
{
    public string Identifier { get; }
    public ImmutableArray<IExpr> Arguments { get; }
}
```

Then, as I mentioned above, changing the `Call` parser to be a _term_, rather than an _operator_, should produce the correct behaviour.

```csharp
static Parser<char, IExpr> Call(Parser<char, IExpr> expr)
    => Identifier
        .Then(
            Parenthesised(expr.Separated(Tok(","))),
            (id, args) => new Call(id, args.ToImmutableArray())
    );

public static readonly Parser<char, IExpr> Expr = ExpressionParser.Build<char, IExpr>(
    expr => OneOf<char, IExpr>(
        Try(Call(expr)),
        Parenthesised(expr).Labelled("parenthesised expression"),
        Literal,
        Identifier
    ),
    new OperatorTableRow<char, IExpr>[]
    {
        Operator.Prefix(Neg).And(Operator.Prefix(Complement)),
        Operator.InfixR<char, IExpr>(Dereference),
        Operator.InfixL(Mul),
        Operator.InfixL(Div),
        Operator.InfixL(Add),
        Operator.InfixL(Sub)
    }
).Labelled("expression");
```

Hope this helps you understand the issue!
