### ISSUE TITLE
Query parser

### ISSUE THREAD

**Issue by pavelvondrasek** [benjamin-hodgson/Pidgin#97]
Hi,

I created parser which parses string like this: `product(select=_id,name,intro;locale=en),person(select=firstName,lastName)`

Now I'm using ; for separation of clauses I would like to use , (comma) instead of ; but I don't know how to do that beacause if I change it it parses locale as field. Can you help me please?

This is my code:

```cs
        private static readonly Parser<char, char> Comma = Char(',');
        private static readonly Parser<char, char> Lp = Char('(');
        private static readonly Parser<char, char> Rp = Char(')');
        private static readonly Parser<char, char> Eq = Char('=');
        private static readonly Parser<char, char> Dot = Char('.');
        private static readonly Parser<char, char> Semicolon = Char(';');

        private static readonly Parser<char, string> Name =
            Token(t => char.IsLetterOrDigit(t) || t == '_').Between(SkipWhitespaces).ManyString();

        private static readonly Parser<char, Operator> Operator =
            from op in Dot.Then(OneOf(String("eq")).Or(String("desc")))
            from value in Dot.Then(Token(char.IsLetterOrDigit).ManyString()).Optional()
            select new Operator(Enum.Parse<Operator.OperatorType>(op, true), value.GetValueOrDefault());

        private static readonly Parser<char, Field> Field =
            from name in Name
            from resources in Resource.Separated(Comma).Between(Lp, Rp).Optional()
            from op in Operator.Optional()
            select new Field(name, resources.GetValueOrDefault(),
                op.GetValueOrDefault() != null ? new[] { op.GetValueOrDefault() } : null);

        private static readonly Parser<char, Clause> Clause =
            from clause in OneOf(Name).Before(Eq)
            from fields in Field.Separated(Comma)
            select clause switch
            {
                "select" => new Clause.SelectClause(fields),
                "where" => new Clause.WhereClause(fields),
                "order" => new Clause.OrderClause(fields),
                _ => new Clause(clause, fields)
            };

        private static readonly Parser<char, Resource> Resource =
            from name in Name
            from clauses in Clause.Separated(Semicolon).Between(Lp, Rp).Optional()
            select new Resource(name, clauses.GetValueOrDefault());

        private static readonly Parser<char, Query> Query =
            from resources in Resource.Separated(Comma)
            select new Query(resources);

        public static Result<char, Query> Parse(string input) => Query.Parse(input);
```

Thank you!
Pavel

**Comment by benjamin-hodgson** [comment]
Sounds like a name is the start of a new `Clause` (and not a `Field`) if it's followed by an `=`. So you could define `Field`'s parser to look for a name which _isn't_ followed by an `=`. Something like `from name in Name.Then(Not(Lookahead(Eq)))`. Does that help?

**Comment by pavelvondrasek** [comment]
Yes, I don't know how to express in parser that fields name isn't followed by an `=` :)

I tried to use `Not` and `Lookahead`
<img width="785" alt="Screenshot 2021-02-12 at 23 25 08" src="https://user-images.githubusercontent.com/7081340/107828790-dbc4ff80-6d89-11eb-8ebd-aa6c01713dae.png">

It doesn't help :(

Thank you.
Pavel

**Comment by benjamin-hodgson** [comment]
It’s just a type error. Replace `Then` with `Before`

**Comment by pavelvondrasek** [comment]
Now it compiles
<img width="767" alt="Screenshot 2021-02-12 at 23 53 18" src="https://user-images.githubusercontent.com/7081340/107831067-81c63900-6d8d-11eb-87b8-63bc7ec53cf6.png">

But parser returns:
<img width="530" alt="Screenshot 2021-02-12 at 23 52 37" src="https://user-images.githubusercontent.com/7081340/107831097-9276af00-6d8d-11eb-879d-d53dd56998af.png">

**Comment by benjamin-hodgson** [comment]
You probably need a `Try` somewhere

**Comment by pavelvondrasek** [comment]
Hmmm, I don't know will try today :)

Thank you!
