### ISSUE TITLE
IEnumerator or IEnumerable?

### ISSUE THREAD

**Issue by Andrew-Webb** [benjamin-hodgson/Pidgin#98]
I have just started to eye up Pidgin as a possible means of implementing [SCIM filter query parsing](https://tools.ietf.org/html/rfc7644#section-3.4.2.2).

I wondered about something I came across on the front page / readme of the repo:-

"Pidgin's core type, Parser<TToken, T>, represents a procedure which consumes an input stream of TTokens, and may either fail with a parsing error or produce a T as output. You can think of it as:

`delegate T? Parser<TToken, T>(IEnumerator<TToken> input);`
"

Should this be `delegate T? Parser<TToken, T>(IEnumerable<TToken> input);` ?  If not, why not?

**Comment by benjamin-hodgson** [comment]
`IEnumerator` is correct. A parser always makes only a single pass over the input (any buffering required for backtracking is internal). `IEnumerable` would imply that it's possible the parser would enumerate multiple times.

**Comment by Andrew-Webb** [comment]
That's very interesting and revealing.  Thanks for clearing that up.
